captcha_dict = [
	#3
	'GOO', 'MUD', 'COP', 'WAR', 'BEN',
	'EYE', 'ARM', 'LEG', 'BOO', 'DAB',
	'KFC', 'GAY', 'LOL', 'GUN', 'MUK',
	'POW', 'WOW', 'POP', 'OWO', 'HIP',
	'END', 'HAT', 'CUP', '911', '711',
	'SIX', 'SMG', 'BOW', 'AWO',
	#4
	'GOON', 'DOOR', 'CORP', 'SPAM', 'BLAM',
	'FISH', 'MINE', 'LOCK', 'OURS', 'ROCK',
	'DATA', 'LOOK', 'GOTO', 'COIN', 'GANG',
	'HEHE', 'WEED', 'LMAO', 'EPIC', 'NICE',
	'SOUL', 'KILL', 'FREE', 'GOOP', 'CAVE',
	'ZOOM', 'FIVE', 'NINE', 'BASS', 'FIRE',
	'TEXT', 'AWOO',
	#5
	'SLIME', 'BOORU', 'ROWDY', 'GHOST', 'ORDER',
	'SCARE', 'BULLY', 'FERRY', 'SAINT', 'SLASH',
	'SLOSH', 'PARTY', 'JUVIE', 'BASED', 'TULPA',
	'SLURP', 'MONTH', 'SEVEN', 'BRASS', 'MINES',
	'GREEN', 'LIGHT', 'FURRY', 'PIZZA', 'ARENA',
	'LUCKY', 'RIFLE', '56709', 
	#6
	'SLUDGE', 'KILLER', 'MUNCHY', 'BLAAAP', 'BARTER',
	'ARTIST', 'FUCKER', 'MINING', 'SURVEY', 'THRASH',
	'BEWARE', 'STOCKS', 'COWARD', 'CRINGE', 'INVEST', 
	'BUSTAH', 'KILLAH', 'KATANA', 'GHOSTS', 'BASSED', 
	'REVIVE', 'BATTLE', 'PAWPAW', 
	#7
	'KINGPIN', 'ENDLESS', 'ATTACKS', 'FUCKERS', 'FISHING',
	'VIOLENT', 'SQUEEZE', 'LOBSTER', 'WESTERN', 'EASTERN', 
	'REGIONS', 'DISCORD', 'KNUCKLE', 'MOLOTOV', 'SHAMBLE',
	'WARFARE', 'BIGIRON', 'POUDRIN', 'PATRIOT', 'MINIGUN',
	
	#8
	'GAMEPLAY', 'SHAMBLER', 'CONFLICT', 'EXCHANGE', 'FEEDBACK',
	'VIOLENCE', 'TACOBELL', 'PIZZAHUT', 'OUTSKIRT', 'WHATEVER',
	'WITHDRAW', 'SOUTHERN', 'NORTHERN', 'ASTATINE', 'SLIMEOID',
	'SHAMBLIN', 'STAYDEAD', 'JUVENILE', 'DOWNTOWN', 'DISTRICT',
	'BIGBONES', 'LONEWOLF', 'KEENSMELL', 'RAZORNUTS', 'REVOLVER',
	'BASEBALL', 'GRENADES', 
	#9
	'APARTMENT', 'SURVIVORS', 'NEGASLIME', 'COMMUNITY', 'GIGASLIME',
	'DETENTION', 'CATHEDRAL', 'TOXINGTON', 'SLIMEGIRL', 'INVESTING',
	'SLIMECOIN', 'RATELIMIT', 'NARRATIVE', 'COMMANDO', 'SHAMBLERS',
	'NUNCHUCKS', 'SLIMECORP', 'ARSONBROOK','SMOGSBURG', 'SLIMEFEST', 
	'COMMANDER', 'FATCHANCE', 'DANKWHEAT', 
	#10
	'SLUDGECORE', 'LOREMASTER', 'ROUGHHOUSE', 'GLOCKSBURY', 'CALCULATED',
	'PLAYGROUND', 'NEWYONKERS', 'OLDYONKERS', 'VANDALPARK', 'SLIMERMAID',
	'SLIMEXODIA', 'WEBBEDFEET', 'NOSEFERATU', 'BINGEEATER', 'TRASHMOUTH',
	'DIREAPPLES', 'BLACKLIMES', 'POKETUBERS', 'PULPGOURDS', 'ROWDDISHES',
	'DRAGONCLAW', 
]