
dance_responses = [
	"{} busts a move. Wow, look at 'em go!",
	"{} gets down and boogies! Groovy!",
	"{} does a headstand and does a 720 degree spin!",
	"{} starts flossing fast and hard!",
	"{} does the Orange Justice, nailing each step flawlessly. Incredible!",
	"{} cracks the whip! Watch them go at it!",
	"{} performs the Nae Nae! https://en.wikipedia.org/wiki/Nae_Nae",
	"{} does the Default Dance! You hear the familiar Fortnite jingle go off in your head.",
	"{} gets down on the floor and does the worm! Their rhythm is off the charts!",
	"{} spins around like a Laotian Toprock dancer! Whoa, be careful not to kick anyone, big guy!",
	"{} does the monkey! Man, they're pretty!",
	"{} does the charleston. What is this, the 20's? They do look kinda cool though...",
	"{} starts breakdancing, Capoeira style! They almost knock someone's teeth out with their swift leg swings!",
	"{} does a triple backflip! Hot diggedy!",
	"{} performs a double Cartwheel! Not really a dance move, but we'll take it!",
	"{} starts a Conga line! The party's over here!",
	"{} does a moonwalk! They're smooth as heck!",
	"{} does the robot! They manage to pull it off in a way that doesn't seem totally autistic!",
	"{} does the carlton! It's anything BUT unusual!",
	"{} starts tap dancing! They really start puttin' on the ritz for sure!",
	"{} pumps their fist in the air over and over!",
	"{} does a Flamenco dance! Their grace and elegance is unmatched!",
	"{} walks like an Egyptian! Wow, racist much???",
	"{} does an old-fashioned breakdance! Hot damn!",
	"{} does the traditional Ukrainian Hopak! Their legs flail back and forth!",
	"{} performs the Mannrobics taunt! They feel the burn!",
	"{} gets the urge to !dab, but holds back with all their might.",
	"{} gets the urge to !thrash, but holds back with all their might.",
	"{} just kind of stands there, awkwardly. What did you expect?",
	"{} makes a complete fool of themselves. Everyone gets secondhand embarrassment...",
	# "{} does the Mayor Pete dance!", -- hm, maybe not...
]
