

# If a fish doesn't bite, send one of these.
nobite_text = [
	"You patiently wait...",
    	"This is so fucking boring...",
    	"You watch your hook bob...",
    	"You grow impatient and kick the rotted wooden guard rails...",
    	"AUUUUUGH JUST BITE THE FUCKING HOOK ALREADY...",
    	"You begin to zone-out a bit...",
    	"Shouldn't you be doing something productive?",
   	"You sit patiently, eagerly awaiting a fish to bite. Thanks to your concentration, this descriptive contradiction does not occur to you.",
    	"You begin to daydream about fish sex... Gross...",
    	"You begin to daydream about fish sex... Hot...",
    	"You see a fish about to bite your hook, but you shout in elation, scaring it away...",
    	"You make direct eye contact with a fish, only to quickly look away...",
    	"♪ Fishing for Fishies! ♪",
    	"♪ That Captain Albert Alexander! ♪",
    	"You get the urge to jump in and try to grab a fish, before remembering that you can't swim...",
    	"You hum some sea shanties...",
    	"You start to slip into an existential crisis...",
    	"You jitter as other seamen catch fish before you. Fuck fishing...",
    	"You feel the oncoming downward spiral...",
    	"You shake your head as a young seaman baits a perfectly good slice of pizza on his hook... What a cretin...",
    	"You wonder if the Space Navy has been formed yet...",
    	"Man... Why were you excited for this shit?",
    	"Still better than Minesweeper...",
    	"Maybe one day your wife will pardon you...",
    	"Fuck fish...",
    	"You let out a deep sigh, scaring away a fish...",
    	"Wouldn't it be funny if you just reached into the sea and grabbed one? Haha, yeah, that'd be funny...",
    	"You see a bird carry off a Plebefish in the distance... Good riddance...",
    	"You spot a stray bullet in the distance...",
    	"You see a dead body float up to the surface of the Slime...",
    	"Fish..."
]
