from ewcosmeticitem import EwCosmeticItem

# List of all cosmetics, purely a list. Item definitions are done in ewitem_cfg.py

cosmetic_id_raincoat = "raincoat"

cosmetic_items_list = [
	EwCosmeticItem(
		id_cosmetic = "propellerhat",
		str_name = "propeller hat",
		str_desc = "A simple multi-color striped hat with a propeller on top. A staple of every juvenile’s youth.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat = True,
	),
	EwCosmeticItem(
		id_cosmetic = "mininghelmet",
		str_name = "mining helmet",
		str_desc = "A typical construction hard hat with a head lamp strapped onto it.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat = True,
	),
	EwCosmeticItem(
		id_cosmetic = "pickelhaube",
		str_name = "pickelhaube",
		str_desc = "A traditional Prussian spiked helmet from the nineteenth century.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "fedora",
		str_name = "fedora",
		str_desc = "A soft brimmed hat with a pinched crown. A classic piece of vintage Americana and a staple of film noir. Not to be confused with the trilby, the fedora is a hat befitting the hardboiled men of it’s time.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "baseballcap",
		str_name = "baseball cap",
		str_desc = "A classic baseball cap. A staple of American culture and subsequently freedom from tyranny. If you don’t own at least one of these hats you might as well have hopped the fence from Tijuana last night. Yeah, I’m racist, that going to be a problem for you??",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "backwardsbaseballcap",
		str_name = "backwards baseball cap",
		str_desc = "A classic baseball cap… with an urban twist! Heh, 'sup dawg? Nothing much, man. You know me, just mining some goddamn slime. Word 'n shit. Hell yeah.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "piratehat",
		str_name = "pirate hat",
		str_desc = "A swashbuckling buccaneer’s tricorne, stylized with a jolly roger on the front.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "eyepatch",
		str_name = "eyepatch",
		str_desc = "A black eyepatch. A striking accessory for the particularly swashbuckling, chauvinistic, or generally hardboiled of you. Genuine lack of two eyes optional and not recommended.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "cigarette",
		str_name = "cigarette",
		str_desc = "A single cigarette sticking out of your mouth. You huff these things down in seconds but you’re never seen without one. Everyone thinks you’re really, really cool.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "headband",
		str_name = "headband",
		str_desc = "A headband wrapped tightly around your forehead with long, flowing ends.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "handkerchief",
		str_name = "handkerchief",
		str_desc = "A bandanna tied on your head, creating a simple cap.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "bandanna",
		str_name = "bandanna",
		str_desc = "A handkerchief tied around your neck and covering your lower face.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "pairofsunglasses",
		str_name = "pair of sunglasses",
		str_desc = "An iconic pair of black sunglasses. Widely recognized as the coolest thing you can wear.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "pairofglasses",
		str_name = "pair of glasses",
		str_desc = "A simple pair of eyeglasses. You have perfectly serviceable eyesight, but you are a sucker for the bookworm aesthetic. People with actual issues with sight hate you.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "birthdayhat",
		str_name = "birthday hat",
		str_desc = "A striped, multi-color birthday hat. ",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "scarf",
		str_name = "scarf",
		str_desc = "A very thick striped wool scarf, in case 110° degrees is too nippy for you.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		str_name = "witch hat",
		id_cosmetic = "witchhat",
		str_desc = "A pointy, cone-shaped hat with a wide brim. It exudes a spooky essence.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "bomberhat",
		str_name = "bomber hat",
		str_desc = "A thick fur and leather aviator’s hat.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "tuxedo",
		str_name = "tuxedo",
		str_desc = "A classy, semi-formal suit for dashing rogues you can’t help but love. Instant charisma granted upon each !adorn.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "beanie",
		str_name = "beanie",
		str_desc = "A simple beanie with a pointed top and a slip stitch brim.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "jestershat",
		str_name = "jester's hat",
		str_desc = "A ridiculous, multi-colored hat with four bells dangling from protruding sleeves.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "pairof3dglasses",
		str_name = "pair of 3D glasses",
		str_desc = "A pair of totally tubular, ridiculously radical 3D glasses. Straight up stereoscopic, dude!",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "necktie",
		str_name = "necktie",
		str_desc = "A vintage necktie, reeking of coffee, college, and shaving cream.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "vikinghelmet",
		str_name = "viking helmet",
		str_desc = "A pointy bronze helmet with two sharp horns jutting out of the base.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "pairofflipflops",
		str_name = "pair of flip flops",
		str_desc = "A pair of loud, obnoxious flip flops. The price of your comfort is higher than you could ever know.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "fez",
		str_name = "fez",
		str_desc = "A short fez with a tassel attached to the top. Fezzes are cool. Or, are bowties cool? You forget, and frankly you’re embarrassed you remember either one of them.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "bowtie",
		str_name = "bowtie",
		str_desc = "A quite dapper, neatly tied butterfly bowtie. Bowties are cool. Or, are fezzes cool? You forget, and frankly you’re embarrassed you remember either one of them.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "cowboyhat",
		str_name = "cowboy hat",
		str_desc = "An essential piece of Wild West memorabilia, a bonafide ten gallon Stetson. Befitting the individualistic individuals that made them famous. Yeehaw, and all that stuff.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "kepi",
		str_name = "kepi",
		str_desc = "A short kepi with a sunken top and an insignia on the front.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "tamoshanter",
		str_name = "tam o' shanter",
		str_desc = "A traditional Scottish wool bonnet with a plaid pattern.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "ushanka",
		str_name = "ushanka",
		str_desc = "A traditional Russian fur cap with thick wool ear flaps.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "karategi",
		str_name = "karategi",
		str_desc = "A traditional Japanese karateka’s outfiit, complete with a belt with extended ends that easily flow in the wind for dramatic effect.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "turban",
		str_name = "turban",
		str_desc = "A traditional Arabian headdress, lavishly decorated with a single large jewel and protruding peacock feather.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "nemes",
		str_name = "nemes",
		str_desc = "The traditional ancient Egyptian pharaoh's striped head cloth.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "varsityjacket",
		str_name = "varsity jacket",
		str_desc = "An American baseball jacket, with a large insignia on the left side of the chest.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "sombrero",
		str_name = "sombrero",
		str_desc = "A traditional Mexican sombrero, with an extra-wide brim to protect you from the blistering Arizonian sun.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "hawaiianshirt",
		str_name = "hawaiian shirt",
		str_desc = "A brightly colored Hawaiian shirt with a floral pattern. It reeks of slima colada and the complementary shampoo from the resort in Assault Flats Beach.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "fursuit",
		str_name = "fursuit",
		str_desc = "A fursuit. Custom-made and complete with high quality faux fur, padded digitigrade legs, follow-me eyes, adjustable facial expressions, and a fan in the head. It is modeled off your original character, also known as your fursona. Some would call its character design “ugly” or “embarrassing,” but you think it's perfect.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 1000000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "diadem",
		str_name = "diadem",
		str_desc = "The traditional Greco-Roman laurel wreath symbolizing sovereignty and power. Be careful about wearing this around in public, you might just wake up with 23 stab wounds.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 1000000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "billshat",
		str_name = "Bill's Hat",
		str_desc = "A military beret with a shield insignia on the front.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 1000000,
		vendors = [vendor_bazaar],
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "weddingring",
		str_name = "wedding ring",
		str_desc = "A silver ring with a decently large diamond on top. For the person you love most in the entire world. <3",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 1000000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "earbuds",
		str_name = "earbuds",
		str_desc = "A pair of white standard iPod earbuds. Who knows what sort of tasty jams you must be listening to while walking down the street?",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 1000000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "nursesoutfit",
		str_name = "nurse's outfit",
		str_desc = "A disturbingly revealing nurse’s outfit that shows off your lumpy, fleshy visage. No one likes that you wear this. Theming bonus for responding to people’s crackpot ideas in the nurse’s office, though.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "heartboxers",
		str_name = "heart boxers",
		str_desc = "A staple of comedy. A pair of white boxers with stylized cartoon hearts tiled all over it. Sure hope your pants aren’t hilariously ripped or unadorned while you’re wearing these, how embarrassing! Hahaha! We like to have fun here.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "captainshat",
		str_name = "Captain's Hat",
		str_desc = "The perfect hat for sailing across the Slime Sea, commanding a navy fleet, or prematurely ending your lucrative My Little Pony review series in favor of starting a shitty Pokemon Nuzlocke series. For shame.",
		acquisition = acquisition_milling,
		ingredients = item_id_poketubers,
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "juveolantern",
		str_name = "Juve-O'-Lantern",
		str_desc = "Hand-carved with a hole just barely big enough to fit your head in, this Juve O' Lantern severely hinders your combat ability. But, you look fucking sick while wearing it, so who cares.",
		acquisition = acquisition_milling,
		ingredients = item_id_pulpgourds,
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "bowlerhat",
		str_name = "Bowler Hat",
		str_desc = "A simply traditional billyock. You’re gonna be the talk of the toy box with this dashing felt cosmetic! Now you just have to work on the moustache.",
		acquisition = acquisition_milling,
		ingredients = item_id_sourpotatoes,
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "cabbagetreehat",
		str_name = "Cabbage Tree Hat",
		str_desc = "An unmistakably Australian hat, with a wide brim and a high crown.",
		acquisition = acquisition_milling,
		ingredients = item_id_bloodcabbages,
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "braces",
		str_name = "Braces",
		str_desc = "An old fashioned orthodontic headgear. Elaborate metal wires and braces hold your nearly eroded, crooked teeth together in what can genously be called a mouth. You are in agony, and so is everyone that looks at you.",
		acquisition = acquisition_milling,
		ingredients = item_id_joybeans,
	),
	EwCosmeticItem(
		id_cosmetic = "hoodie",
		str_name = "Hoodie",
		str_desc = "Perfect for keeping warm in the middle of the blisteringly hot Arizonian desert! Heatstroke or bust!",
		acquisition = acquisition_milling,
		ingredients = item_id_purplekilliflower,
	),
	EwCosmeticItem(
		id_cosmetic = "copbadge",
		str_name = "Cop Badge",
		str_desc = "What the fuck are you doing with this thing? Are you TRYING to make the sewers your permanent residence? Acquaint yourself with the !drop command and FAST, before you don’t have a body to wear the badge on.",
		acquisition = acquisition_milling,
		ingredients = item_id_razornuts,
	),
	EwCosmeticItem(
		id_cosmetic = "strawhat",
		str_name = "Straw Hat",
		str_desc = "A wide-brimmed straw hat, the perfect hat for farming.",
		acquisition = acquisition_milling,
		ingredients = item_id_pawpaw,
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "cosplayhorns",
		str_name = "Cosplay Horns",
		str_desc = "You’re not entirely sure what these things are, but they sort of look like brightly painted, candy corn colored, paper mache horns that are hot glued onto a black headband. Their purpose is mysterious, but for some reason you are inclined to adorn them… perhaps you understood their importance in a past life.",
		acquisition = acquisition_milling,
		ingredients = item_id_sludgeberries,
	),
	EwCosmeticItem(
		id_cosmetic = "youfavoritehat",
		str_name = "***Your Favorite Hat***",
		str_desc = "***It fits perfectly, and it’s just your style! You love wearing this cosmetic far more than any other, it’s simply the best.***",
		acquisition = acquisition_milling,
		ingredients = item_id_suganmanuts,
		is_hat=True,
	),
	EwCosmeticItem(
		id_cosmetic = "pajamaonesie",
		str_name = "Pajama Onesie",
		str_desc = "A soft jumpsuit with an audacious, repeating design printed over the entire cosmetic. You feel like getting a little bit fucking rowdy wearing this outrageous onesie. ",
		acquisition = acquisition_milling,
		ingredients = item_id_pinkrowddishes,
	),
	EwCosmeticItem(
		id_cosmetic = "pairofcircularsunglasses",
		str_name = "Pair of Circular Sunglasses",
		str_desc = "Sunglasses, but in a circle! Genius! You can't wait to show the world your hot takes on television shows for girls.",
		acquisition = acquisition_milling,
		ingredients = item_id_dankwheat,
	),
	EwCosmeticItem(
		id_cosmetic = "flowercrown",
		str_name = "Flower Crown",
		str_desc = "A lovingly handcrafted crown of flowers, connected by a string. You’re gonna be famous on Pinterest with a look like this!",
		acquisition = acquisition_milling,
		ingredients = item_id_brightshade,
	),
	EwCosmeticItem(
		id_cosmetic = "spikedbracelets",
		str_name = "Spiked Bracelets",
		str_desc = "Hilariously unrealistic spiked bracelets, ala Bowser, King of the Koopas. You’re hyper aware of these fashion disasters whenever you’re walking, making sure to swing them as far away from your body as possible.",
		acquisition = acquisition_milling,
		ingredients = item_id_blacklimes,
	),
	EwCosmeticItem(
		id_cosmetic = "slimecorppin",
		str_name = "SlimeCorp Pin",
		str_desc = "An enamel pin of the SlimeCorp logo, a badge of loyalty to your favorite charismatic megacorporation. Dude, like, *”Follow He Who Turns The Wheels”*, bro!!",
		acquisition = acquisition_milling,
		ingredients = item_id_phosphorpoppies,
	),
	EwCosmeticItem(
		id_cosmetic = "overalls",
		str_name = "Overalls",
		str_desc = "Simple, humble denim overalls, for a simple, humble farmer such as yourself.",
		acquisition = acquisition_milling,
		ingredients = item_id_direapples,
	),
	EwCosmeticItem(
		id_cosmetic = cosmetic_id_raincoat,
		str_name = "Raincoat",
		str_desc = "A specially engineered piece of personal armor, that protects you from the deadly threat from above.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 50000,
		vendors = [vendor_bazaar],
	),
	EwCosmeticItem(
		id_cosmetic = "halloweenmedallion",
		str_name = "Double Halloween Medallion",
		str_desc = "A glistening crystal medallion, carved in the shape of a pumpkin. It is strewn together with black pearls. Awarded only to the bravest of souls who managed to best the Double Headless Double Horseman in combat.",
		rarity = "Double Halloween",
		acquisition = "DH-bossfight",
		ingredients = "HorsemanSoul" # used here as a substitute for the 'context' attribute found on general items.
	),
	EwCosmeticItem(
		id_cosmetic = "pileus",
		str_name = "Pileus",
		str_desc = "A symbol of freedom and liberty. In ancient times, these felt caps were given to slaves who had been emancipated.",
		rarity = rarity_plebeian,
	#	vendors = [vendor_bazaar, vendor_college],
		price = 100,
	),
	EwCosmeticItem(
		id_cosmetic = "seacowcostume",
		str_name = "Attractive Gray Sea Cow Mascot Costume for Adult",
		str_desc = "Attractive. That's really all there is to say on the matter.",
		rarity = rarity_promotional,
		vendors = [vendor_bazaar],
		price = 100000000,
	),
	EwCosmeticItem(
		id_cosmetic = "wrappingpaperhat",
		str_name = "Wrapping Paper Hat",
		str_desc = "A hat made out of wrapping paper, fashioned in a way rather similar to a newspaper hat. How festive!",
		rarity = rarity_plebeian,
		vendors = [vendor_glocksburycomics],
		price = 1000,
	),
        EwCosmeticItem(
		id_cosmetic = "knightarmor",
		str_name = "Steel knight armor",
		str_desc = "A shining set of steel armor.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		is_hat = True,
	),
]


# A map of id_cosmetic to EwCosmeticItem objects.
cosmetic_map = {}

# A list of cosmetic names.
cosmetic_names = []


