furniture_list = [
EwFurniture(
		id_furniture = "interrogationchair",
		str_name = "interrogation chair",
		str_desc = "This is the kind of chair shitty cops use to question their victims. Sitting in it gives you war flashbacks to when you were arrested, so you'll probably only whip it out for special occasions.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 100000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's an interrogation chair here for some reason.",
		furniture_place_desc = "You place the chair in the middle of the room, trying not to think about police."),
EwFurniture(
		id_furniture = "brokenclock",
		str_name = "broken clock",
		str_desc = "You can't believe you own and treasure a broken clock. The bazaar sells these by convincing idiotic juvies they can fix it. They can't.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 200,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The broken clock says it's 2:33.",
		furniture_place_desc = "You hang the clock on the wall."),
EwFurniture(
		id_furniture = "bevanssnot",
		str_name = "Bevan's snot",
		str_desc = "This stuff is actually pretty useful. It's a way to decorate your house with slime, without actually having to give up your own.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 2000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The walls are smeared with slime.",
		furniture_place_desc = "You gently smear the slime facsimile on the walls."),
EwFurniture(
		id_furniture = "chair",
		str_name = "chair",
		str_desc = "It's a normal wooden chair. A sign of your entry into the rat race that is the economy.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 40000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a chair in the room.",
		furniture_place_desc = "You set the chair where you think it's appropriate. How exciting."),
EwFurniture(
		id_furniture = "desk",
		str_name = "desk",
		str_desc = "A normal wooden desk. You can almost hear your soul breaking under your monotonous career.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 80000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "You see a desk in the corner.",
		furniture_place_desc = "You set up the desk in the corner of the room."),
EwFurniture(
		id_furniture = "couch",
		str_name = "couch",
		str_desc = "This one's a pull-out couch. The upholstery is pretty new, yet somehow looks worn out already.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 120000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a comfy couch up against the wall.",
		furniture_place_desc = "You get some friend or another to help you move the couch in. They pretended like they were happy to do it, but you know they weren't."),
EwFurniture(
		id_furniture = "lamp",
		str_name = "lamp",
		str_desc = "A normal lamp. Good for reading, if your juvenile delinquent ass could actually read.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 10000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The lamp casts a warm light throughout the room.",
		furniture_place_desc = "You set up the lamp, plug it in, and watch the one-light light show."),
EwFurniture(
		id_furniture = "lgbtqdesk",
		str_name = "LGBTQ+ desk",
		str_desc = "It's like a regular desk, but the drawers are all different colors of the rainbow.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 160000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A gaudy rainbow desk is in the corner of the room.",
		furniture_place_desc = "You drag the desk into position. You feel gayer already.",
		furn_set = "lgbt"),
EwFurniture(
		id_furniture = "lgbtqchair",
		str_name = "LGBTQ+ chair",
		str_desc = "A rainbow striped chair. I'll bet you could give some pretty good man-on-man lap dances with this.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 40000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a rainbow chair set up.",
		furniture_place_desc = "You place the chair in the best place you can think of.",
		furn_set = "lgbt"),
EwFurniture(
		id_furniture = "lgbtqcouch",
		str_name = "LGBTQ+ couch",
		str_desc = "There's no need for this couch to pull out.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 240000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A colorful couch sits against the wall.",
		furniture_place_desc = "You contact the Village People, and they help you move the couch in. Those guys are pretty helpful.",
		furn_set = "lgbt"),
EwFurniture(
		id_furniture = "lgbtqlamp",
		str_name = "LGBTQ+ lamp",
		str_desc = "It's not actually the lamp that's LGBTQ. It's the bulb.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 10000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The fancy lamp flashes rainbow everywhere.",
		furniture_place_desc = "You plug in the lamp and watch the pretty colors for awhile.",
		furn_set = "lgbt"),
EwFurniture(
		id_furniture = "lgbtqbed",
		str_name = "LGBTQ+ bed",
		str_desc = "This is where the magic happens.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 300000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a rainbow bed in the bedroom.",
		furniture_place_desc = "You set up your bed, dreaming of all the same-sex poon you're gonna slam.",
		furn_set = "lgbt"),
EwFurniture(
		id_furniture = "bed",
		str_name = "bed",
		str_desc = "A standard-issue bed, ready-made for crying yourself to sleep.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 150000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a bed in the bedroom.",
		furniture_place_desc = "The IKEA instructions are confusing, so it takes a few attempts to make the bed."),
EwFurniture(
		id_furniture = "hauntedbed",
		str_name = "haunted bed",
		str_desc = "This bed was owned by a long-gone staydead, way back in Season 1. You can still feel the negaslime residue on it.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 300000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "You hear ghostly moaning from the bedroom.",
		furniture_place_desc = "You're about to place the mattress when a dozen spiders crawl out of it. Better be careful with this one.",
		furn_set = "haunted"),
EwFurniture(
		id_furniture = "hauntedcouch",
		str_name = "haunted couch",
		str_desc = "Every person who sat on this couch was supposedly cursed to die the day after. That doesn't mean much in NLACakaNM, though.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 240000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The rustic couch against the wall looks old and haunted.",
		furniture_place_desc = "You were going to ask some of your buds to help move this in, but you walked into the apartment and it was already there...",
		furn_set = "haunted"),
EwFurniture(
		id_furniture = "hauntedlamp",
		str_name = "haunted lamp",
		str_desc = "When you turn on this lamp it somehow makes the room darker.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 20000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The lighting in here is ominous, thanks to your lamp.",
		furniture_place_desc = "You set up the old lamp. The light flickers.",
		furn_set = "haunted"),
EwFurniture(
		id_furniture = "hauntedchair",
		str_name = "haunted chair",
		str_desc = "This chair doesn't seem to go well with other furniture, unless it's below a noose.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 40000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A creepy chair stands in the middle of the room.",
		furniture_place_desc = "You put the chair out of sight, where you won't be tempted to !suicide.",
		furn_set = "haunted"),
EwFurniture(
		id_furniture = "haunteddesk",
		str_name = "haunted desk",
		str_desc = "It just looks like an old desk. What did the store clerk mean by 'haunted'?",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 160000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "An old desk(haunted, apparently) is in the corner.",
		furniture_place_desc = "You move the desk into the corner. Scary.",
		furn_set = "haunted"),
EwFurniture(
		id_furniture = "armageddonspritzer",
		str_name = "Armageddon Spritzer",
		str_desc = "You look at the automatic scent spritzer, filled to the top with a sinister red liquid. You wonder to yourself why you bought this. All of a sudden, it sprays a puff directly into your face, and you begin to hallucinate.\n\nThe light begins to fade from your eyes as you're bombarded with cacophanous mental static. The buzzing and echoey clanging drives you to scream, but your body no longer exists. You try to clutch your face in desperation and all you feel is liquid. You feel burning. Burning everywhere. The sky flashes a dissonant dark orange, as though the sun was setting on reality itself, and although nobody is speaking, you feel it all calling to you. But you don't want this. Whatever memories haven't escaped you want this all to stop. You don't know your own name and you wish to remember it. And it all hurts. It hurts so much. Please stop. Stop. Stop. Stop. Stop. Stop. Stop. Stop. Stop. Stop. Stop. Stop.\n\nWhen you wake up, your face is bleeding and 2 hours have passed. Well, shit. Guess you better prepare for when this goes off again in an hour.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 10000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The spritzer in here makes you feel the sicknasty feelings.",
		furniture_place_desc = "You set up the spritzer high up on the wall. Gulp."),
EwFurniture(
		id_furniture = "beanbagchair",
		str_name = "beanbag chair",
		str_desc = "A cushy chair. You were told Digibro has one just like it.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 200000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A beanbag chair is plopped just wherever.",
		furniture_place_desc = "You plop the beanbag chair just wherever."),
EwFurniture(
		id_furniture = "slimebagchair",
		str_name = "slimebag chair",
		str_desc = "A squishy slime-based chair. It's nice and viscous, for your tired bottom.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A bright green slimebag chair is plopped just wherever.",
		furniture_place_desc = "You plop the slimebag chair just wherever."),
EwFurniture(
		id_furniture = "custombodypillow",
		str_name = "{custom} body pillow",
		str_desc = "A dakimakura with pillowcase. It's got {custom} on it.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 400000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a {custom} body pillow in the bedroom.",
		furniture_place_desc = "You gently place the pillow in your room, being careful not to damage your waifu."),
EwFurniture(
		id_furniture = "futon",
		str_name = "futon",
		str_desc = "Every tenant's best friend. Foldable, holdable, lovable.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 199999,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a futon against the wall.",
		furniture_place_desc = "You get your friends to help you set up the futon. It's so light and convenient that they treat you to KFC at the end of it."),
EwFurniture(
		id_furniture = "vaporsposter",
		str_name = "The Vapors poster",
		str_desc = "It's a poster for The Cop Killer's comic. There's Magda. Yep. \npatreon.com/bensaint\nsaintcomix.com",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 180000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a Vapors poster on the wall.",
		furniture_place_desc = "You roll out your fullbody Magda poster and place it on the wall. You wonder if it's considered a betrayal if Rowdys own these."),
EwFurniture(
		id_furniture = "burgerprintwallpaper",
		str_name = "burger print wallpaper",
		str_desc = "This wallpaper is a dead ringer for that burger jumpsuit the Rowdy Fucker always wears. Just having it makes you feel rancorous.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 180000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The walls are papered with burgers.",
		furniture_place_desc = "You start by taking all your furniture out of your house. You buy a paintroller, some adhesive, and some tarp for the floor. You toil for a day sticking the adhesive and applying the wallpaper, then stay at someone else's flat for another day so it dries. And... dammit, the burgers aren't aligned correctly on the seams. Guess we'll just deal."),
EwFurniture(
		id_furniture = "highclassbed",
		str_name = "high class bed",
		str_desc = "This offensively comfortable little number is filled with grade A down feathers hand-picked by NASA. You can get such good sleep on it that it almost lets you forget your sins. Almost.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 40000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "You glimpse the high class bed in the bedroom and feel the urge to lie down.",
		furniture_place_desc = "You walk outside and give a stern nod to the lower-class peons running about. They give a melancholy look when they see you point to your new bed, but they know they must do as told. Four of the stronger looking street urchins hoist your bed in their arms and carry it to your abode, with you sitting atop it like the emperor you are. They set you down with the gentleness of skilled servants, and you flip them several million SlimeCoin just to get out of your sight. Boy. You can't wait to sleep on this.",
		furn_set = "high class"),
EwFurniture(
		id_furniture = "highclassthrone",
		str_name = "high class throne",
		str_desc = "A golden throne adorned with red velvet. Jewel encrusted, regal, and fucking stupid expensive.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 45000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "You see the throne. It beckons.",
		furniture_place_desc = "As you place the throne, you picture the kings that came before you. Marc Antony. Nero. All six Georges. Or seven, if you count Maddox. Thinking on it, you decide your reign will be different from those idiots.",
		furn_set = "high class"),
EwFurniture(
		id_furniture = "highclasscouch",
		str_name = "high class couch",
		str_desc = "It's a luxury hardwood sofa with huge gemstones in the armrests. As stiff as it looks, it's comfier than anything you've sat in before.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 20000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A high class couch is against the wall.",
		furniture_place_desc = "You hire some people to help you move your couch in. They were way too slow for your busy schedule.",
		furn_set = "high class"),
EwFurniture(
		id_furniture = "highclassdesk",
		str_name = "high class desk",
		str_desc = "They say some old politician signed a bunch of sick ass documents on this. The vendor never told you who, though.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 15000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A high class desk is in the corner.",
		furniture_place_desc = "You place the desk near a window, allowing the serfs outside to bask in your radiance.",
		furn_set = "high class"),
EwFurniture(
		id_furniture = "highclasslamp",
		str_name = "high class lamp",
		str_desc = "It's a lamp. It looks just like the regular lamp, but it doesn't actually work. You got suckered, dude.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 150000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The lamp is broken.",
		furniture_place_desc = "You try all sorts of light bulbs, but the lamp is just broken. You defeatedly set it up where it won't attract attention."),
EwFurniture(
		id_furniture = "laptopcomputer",
		str_name = "laptop computer",
		str_desc = "It's a laptop from 2006, freshly installed with Windows XP. This thing hardly works, but when it's plugged into the wall you can still run Discord.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1500000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A laptop sits closed on the floor.",
		furniture_place_desc = "You place the laptop and plug it in."),
EwFurniture(
		id_furniture = "rainbowdashfigurine",
		str_name = "rainbow dash figurine",
		str_desc = "It's one of those little pony figures from MLP: Friendship is Magic. It's in pretty good condition.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 30000,
		vendors = [],
		furniture_look_desc = "You can sense brony vibes in this room.",
		furniture_place_desc = "You set Rainbow by the windowsill, where she can daydream about taking to the skies.",
		furn_set = "pony"),
EwFurniture(
		id_furniture = "diploma",
		str_name = "framed diploma",
		str_desc = "It's a diploma from a NLACakaNM college. You're not sure you earned this.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 2000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A diploma hangs on the wall.",
		furniture_place_desc = "You think about all the memories you had back in college: drinking, skipping class, killing everyone in University Parking Services, and maybe even a little learning along the way. You lower your head sentimentally and hang the diploma on your wall."),
EwFurniture(
		id_furniture = "racecarbed",
		str_name = "race car bed",
		str_desc = "VROOM VROOM! NNNNEEEEEEOOOOOOWWWWWW SKRRT! NEEEEEEEOOOOOOOOW BEEP BEEP! SCREEECH! CRASH!",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1330000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a racecar bed in the bedroom.",
		furniture_place_desc = "You assemble the bed and place it in your vroom."),
EwFurniture(
		id_furniture = "padlockset",
		str_name = "set of padlocks",
		str_desc = "You have a standard deadbolt lock, a steel door guard, a second password protected deadbolt, one of those chain thingies, reinforced hinges, and one of those dungeon-style full-length door guards. Also a chair to prop against the door for good measure.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 750000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The door is really, REALLY locked.",
		furniture_place_desc = "You meticulously attach your various locks to your front door until you're satisfied with the craftsmanship. Maybe now you'll finally sleep soundly at night."),
EwFurniture(
		id_furniture = "butler",
		str_name = "butler",
		str_desc = "You don't know this man's real name, but he responds to Jeeves so you've been going with that. He does whatever you tell him to do, but for some reason he's useless at gang warfare.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 8000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A butler stands up straight against the wall, awaiting your instructions.",
		furniture_place_desc = "You clap twice, and your butler comes running. You point to the floor in the corner. \"Jeeves,\" you say, \"You'll be sleeping here from now on.\" He nods, and begins to get comfy there on the cold floor."),
EwFurniture(
		id_furniture = "crib",
		str_name = "crib",
		str_desc = "Awwww. I bet your kid looks adorable sleeping in this. You do have a kid, right?",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 650000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a crib in the bedroom.",
		furniture_place_desc = "You build the crib from the little box it came in, spinning the mobile a couple of times to make sure it works."),
EwFurniture(
		id_furniture = "unhealthylivingbook",
		str_name = "Guide to Unhealthy Living: Cowritten by the Rift Cafe",
		str_desc = "It's a book about how to transition to living a sedentary, unhygenic lifestyle in less than 20 days.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 200000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "This place smells awful.",
		furniture_place_desc = "You carefully study brony habit-forming patterns and embrace mediocrity. Your life slowly begins to fall apart, and the junk food you eat permeates the room and makes everything smell like piss and negaslime. You can't believe a product of the Rift Cafe actually accomplished something."),
EwFurniture(
		id_furniture = "singingfishplaque",
		str_name = "singing fish plaque",
		str_desc = "You press the button on the plaque. \n\n:notes:Here's a little tip I know:notes:\n:notes:Take with !snag and store with !stow:notes:\n:notes:Don't worry:notes:\n:notes:Stay slimy:notes:\n:notes:The little miners were upset:notes:\n:notes:So they went and fished me up instead:notes:\n:notes:Don't worry:notes:\n:notes:Stay slimy:notes:\n:notes:WEEEEEEEEEEEEEEEEEEEEEHEEEEEEEEEEEHEEEEEEEEEEEEEHEEHAOOHEEHEHEHOOHAHAHAAAA\n\nFuck, this thing is annoying. You smack it in the face before it finishes its song.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 500000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a fake fish mounted on the wall.",
		furniture_place_desc = "You put a nail in the wall and hang up your fish. Slimecorp probably doesn't want you knocking holes in the walls, but fuck 'em."),
EwFurniture(
		id_furniture = "arcadecabinet",
		str_name = "arcade cabinet",
		str_desc = "It's broken. Shit.", #the description gets replaced with a game link when the buy function trips
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's an arcade cabinet set up.",
		furniture_place_desc = "It's been forever since you've played a real video game. Finally, the moment you've been waiting for. You plug this bitch in and gaze at its splendor."),
EwFurniture(
		id_furniture="washingmachine",
		str_name="washing machine",
		str_desc="It's one of those top-loading machines from ages ago. With this you can !wash <item> to remove the dye from it, but you're not sure you want to. Hygiene doesn't seem very RFCK-core.",
		rarity=rarity_plebeian,
		acquisition=acquisition_bartering,
		price=1600000,
		vendors=[vendor_bazaar],
		furniture_look_desc="An old washing machine is hooked up in the other room.",
		furniture_place_desc="You place the washing machine in a side room. You don't really know how you managed the complex plumbing involved, but there it is."),
EwFurniture(
		id_furniture = "leatherdesk",
		str_name = "leather desk",
		str_desc = "A desk adorned with scalp leather. Looks nice and fancy, as long as you forget how it was made.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's a leathery desk in the corner.",
		furniture_place_desc = "You place the desk and admire the subtle craftsmanship that was put into it.",
		furn_set = "leather"),
EwFurniture(
		id_furniture = "leathercouch",
		str_name = "leather couch",
		str_desc = "It's a leather couch made of human scalps. To be fair, no cow would dare set foot in this city.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "The studded leather couch adds class to the room.",
		furniture_place_desc = "Moving the couch in was a huge pain. Nobody wanted to help you move it, so you had to manage yourself. Christ, it's like just having a scalp-couch makes everybody think you're a serial killer.",
		furn_set = "leather"),
EwFurniture(
		id_furniture = "leatherbed",
		str_name = "leather bed",
		str_desc = "It's a bed upholstered with leather. Demonstrably less comfortable than a regular bed, but you just had to.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's a leather bed in the bedroom.",
		furniture_place_desc = "You set up the bed, slowly spreading the human scalp comforter across its sheets. This isn't as good of an idea as you remember.",
		furn_set = "leather"),
EwFurniture(
		id_furniture = "leatherlamp",
		str_name = "leather lamp",
		str_desc = "The leather covering makes you feel a bit more western. Also the fact that you killed 3 cowpokes just to get it.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "The lamp is adorned with leather.",
		furniture_place_desc = "The leather is soft to the touch, giving you that extra bit of comfort as you plug it in.",
		furn_set = "leather"),
EwFurniture(
		id_furniture = "leatherchair",
		str_name = "leather chair",
		str_desc = "A minor upgrade to the regular chair. Was this even worth it?",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "A nice leather chair is set up.",
		furniture_place_desc = "You set the chair up. You realize you're basically sitting on your enemies' heads and giggle about it.",
		furn_set = "leather"),
EwFurniture(
		id_furniture = "pictureframe",
		str_name = "picture frame",
		str_desc = "https://cdn11.bigcommerce.com/s-cece8/images/stencil/1280x1280/products/305/1506/010420__10394.1343058001.jpg?c=2&imbypass=on",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 90000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A picture frame hangs on the wall.",
		furniture_place_desc = "You place the picture on the wall. What did you put in there? Was it a picture of your family? I bet it was a picture of your family. Man, you suck."),
EwFurniture(
		id_furniture = "hammock",
		str_name = "hammock",
		str_desc = "It's a frayed rope hammock. Kinda looks like the worn-out fishing nets they use down at the piers, but it'll probably work just as well as the real deal.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 370000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "An indoor hammock is set up in the bedroom.",
		furniture_place_desc = "Getting this set up will be tricky. You take some industrial strength railroad spikes and drive them into each side of the wall, then use the supports to wrap the two ends until the hammock is taut. Why the fuck did you set up a hammock indoors, anyway?"),
EwFurniture(
		id_furniture = "juggaloposter",
		str_name = "juggalo poster",
		str_desc = "Violent J and Shaggy 2 Dope are depicted brutally murdering some juvie with steak knives. Their stabbing form is terrible but you can appreciate their charisma.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 100000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A poster on the wall depicts a Juggalo murder party.",
		furniture_place_desc = "You don't have any tape to fasten the poster, so you end up using magnets instead. You're not sure how they work, though. "),
EwFurniture(
		id_furniture = "television",
		str_name = "television",
		str_desc = "It's a CRT, a pretty big one too. A bunch of adapters are frankenstein'd up to it so it takes modern cables.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1500000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "An old CRT is set up.",
		furniture_place_desc = "You drop the TV on the floor. Your parents said this stuff turns your brain to mush, but yours is already slime, so no harm done. Time to get !watching!"),
EwFurniture(
		id_furniture = "pottedplant",
		str_name = "potted plant",
		str_desc = "It's a potted plant. Currently empty.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 10000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A potted plant is on the sill.",
		furniture_place_desc = "You set the pot where plants in it could get plenty of sunlight."),
EwFurniture(
		id_furniture = "airmattress",
		str_name = "air mattress",
		str_desc = "A vinyl air mattress. Perfect for sleepovers, or when the homeless crash at your place.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 420000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "An air matress is blown up in the bedroom.",
		furniture_place_desc = "You blow a whole bunch until your floppy piece of vinyl is a bouncy piece of vinyl."),
EwFurniture(
		id_furniture = "churchpew",
		str_name = "church pew",
		str_desc = "A long wooden bench they normally use in church services. To be completely honest, it looks really uncomfortable to sit in.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 240000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A pew is against the wall.",
		furniture_place_desc = "You set up the pew in your flat, just in case someone wants to hear you preach.",
		furn_set = "church"),
EwFurniture(
		id_furniture = "churchaltar",
		str_name = "church altar",
		str_desc = "An old-looking altar with elaborate carving on the sides. Do you do sacrifices on these?",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 270000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "An altar is fully adorned against the wall.",
		furniture_place_desc = "You place a fresh tablecloth, some incense, and a bible on the altar. You say a hymn to yourself before standing up to admire the handiwork.",
		furn_set = "church"),
EwFurniture(
		id_furniture = "churchcandles",
		str_name = "church candles",
		str_desc = "A 16 pack of beeswax candles and a couple brass candlesticks to go with them.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 110000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The room is dimly lit with candles.",
		furniture_place_desc = "You arrange the candlesticks with a pleasing symmetry. Someone less pious would call this a fire hazard, but you're determined that God won't let your house burn down.",
		furn_set = "church"),
EwFurniture(
		id_furniture = "confessionbooth",
		str_name = "confession booth",
		str_desc = "It's a little pair of rooms you sit in to confess your sins. Living in NLACakaNM you may have a lot of those.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 110000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A confession booth has been installed here.",
		furniture_place_desc = "Once you get the booth in, you make sure it works by confessing to yourself. It does, that's good.",
		furn_set = "church"),
EwFurniture(
		id_furniture = "abstinencebed",
		str_name = "abstinence bed",
		str_desc = "It's like a regular bed, but you're fastened to it to prevent any unneeded fornication. Paradoxically, that's actually sort of kinky.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 300000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "An abstinence bed is in the bedroom.",
		furniture_place_desc = "You place the bed down, dreaming of all that sinful poon you're going to miss out on.",
		furn_set = "church"),
EwFurniture(
		id_furniture = "wallpaper",
		str_name = "wallpaper",
		str_desc = "It's a solid color wallpaper. Pretty plain, but dyeable.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 30000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The walls are a nice shade of -*HUE*-",
		furniture_place_desc = "You cover the walls with wallpaper. ",
		furn_set = "specialhue"),
EwFurniture(
		id_furniture = "applejackfigurine",
		str_name = "apple jack figurine",
		str_desc = "It's an MLP figure. She's a dirty southerner.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 30000,
		vendors = [],
		furniture_look_desc = "You can sense brony vibes in this room.",
		furniture_place_desc = "You place Apple Jack up on the windowsill.",
		furn_set = "pony"),
EwFurniture(
		id_furniture = "fluttershyfigurine",
		str_name = "fluttershy figurine",
		str_desc = "It's an MLP figure. She's a yellow pegasus, very Juvie-core.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 30000,
		vendors = [],
		furniture_look_desc = "You can sense brony vibes in this room.",
		furniture_place_desc = "Fluttershy goes right here on the sill.",
		furn_set = "pony"),
EwFurniture(
		id_furniture = "rarityfigurine",
		str_name = "rarity figurine",
		str_desc = "It's an MLP figure. This one's known for being marginally bitchier than the others.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 30000,
		vendors = [],
		furniture_look_desc = "You can sense brony vibes in this room.",
		furniture_place_desc = "You set Rarity up by the window. Clearly she's above being on the ground. Fucking ornery cunt.",
		furn_set = "pony"),
EwFurniture(
		id_furniture = "pinkiepiefigurine",
		str_name = "pinkie pie figurine",
		str_desc = "It's an MLP figure. You may be hallucinating but its voice keeps speaking inside your head.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 30000,
		vendors = [],
		furniture_look_desc = "You sense Ponk in the room.",
		furniture_place_desc = "You set Pinkie Pie up on the sill and try to suppress the voices in your head.",
		furn_set = "pony"),
EwFurniture(
		id_furniture = "twilightsparklefigurine",
		str_name = "twilight sparkle figurine",
		str_desc = "It's an MLP figure. This one talks big about friendship but has a dragon indentured servant for like the whole show. What a hypocrite!",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 30000,
		vendors = [],
		furniture_look_desc = "You can sense brony vibes in this room.",
		furniture_place_desc = "You place Twilight on the bookshelf. Not that she would enjoy the kind of swill you read.",
		furn_set = "pony"),
EwFurniture(
		id_furniture = "mylittleponyfigurine",
		str_name = "my little pony figurine",
		str_desc = "",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 30000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "You can sense brony vibes in this room.",
		furniture_place_desc = "You place a horse figurine on the windowsill."),
EwFurniture(
		id_furniture = "hatstand",
		str_name = "hat stand",
		str_desc = "A hat stand is by the door.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 200000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A hat stand sits near the door.",
		furniture_place_desc = "You prop the hat stand up and hang whatever hats you can find on top."),
EwFurniture(
		id_furniture = "recordplayer",
		str_name = "record player",
		str_desc = "An antique gramophone from the 1930s. It normally plays vinyl, but through the power of slime, CDs work just as well.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 460000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "An old record player sits on the floor.",
		furniture_place_desc = "You place the ol' boy on the floor."


),
EwFurniture(
		id_furniture = "keg",
		str_name = "keg",
		str_desc = "You managed to buy an entire keg of high proof liquor without even needing to show ID. NLACakaNM is the best city in the world.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 520000,
		vendors = [vendor_bazaar, vendor_bar],
		furniture_look_desc = "The keg in the room looks dulled and dented. Standard, almost.",
		furniture_place_desc = "You take a swig out of the keg and haphazardly roll it across the room. That'll do."
),
EwFurniture(
		id_furniture = "slimecityflag",
		str_name = "Slime City flag",
		str_desc = "There's nothing like the good old stars n' slugs to bring a tear to an old patriot's eye.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 90000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The NLACakaNM flag hangs proudly on the wall",
		furniture_place_desc = "You hang the flag on your wall and sing the anthem aloud to yourself."
),
EwFurniture(
		id_furniture = "slimecityconfederateflag",
		str_name = "Slime City Confederate flag",
		str_desc = "It's an alternate flag design the Rowdys pull out during civil wars. Long live the motherfucking south.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 90000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The NLACakaNM Confederate flag hangs defiantly on your wall.",
		furniture_place_desc = "Shit, let's be Robert E. Lee. You confirm your support of the Confederacy by flying the flag outside your window."
),
EwFurniture(
		id_furniture = "slimeoidhouse",
		str_name = "slimeoid house",
		str_desc = "It's a little hutch for your slimeoid to stay in. It's only knee high though, so it looks like the big ones are SOL.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 400000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "Your slimeoid just loves that slimehouse you set up.",
		furniture_place_desc = "You have to place the slimehouse inside so that it doesn't get caught in any drive-bys. Looks pretty cozy anyway."
),
EwFurniture(
		id_furniture = "humancorpse",
		str_name = "human corpse",
		str_desc = "It's a fresh cadaver, stitched together with the bits and bobs you find regularly on the street. What a find!",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 0,
		vendors = [],
		furniture_look_desc = "There's a dead body in here.",
		furniture_place_desc = "You open the bodybag you've been lugging around and splay the corpse out on it. You're no expert on feng shui, but if Martha Stewart saw this, she would probably run the fuck away. Out of jealousy. "
),
EwFurniture(
		id_furniture = "reanimatedcorpse",
		str_name = "reanimated corpse",
		str_desc = "It's a stitched cadaver you found, reanimated with someone's immortal soul. It cannot speak, but it's obedient enough regardless.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 0,
		vendors = [],
		furniture_look_desc = "A Frankenstein-like creature is chilling in here.",
		furniture_place_desc = "You tell your thrall to kneel over there in the corner. They know what they did."
),
EwFurniture(
		id_furniture = "medievaltorturedevice",
		str_name = "medieval torture device",
		str_desc = "It's an old-style torture machine. This one is called 'The Rack' and you use it to stretch someone until their spine begs for mercy. It usually doesn't work well on slimeoids, what with their amorphous bodies, so somebody retrofitted it with a hot plate on the seat cushion.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 3000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A torture rack is installed in here.",
		furniture_place_desc = "You assemble the torture device and do a couple of test cranks. Putting it together was a bitch and a half because the instructions were in Old English."
),
EwFurniture(
		id_furniture = "blackvelvetsofa",
		str_name = "black velvet sofa",
		str_desc = "It's a sleek, luxurious couch adorned with platinum studded black velvet. They say only the most criminally prone Italians could ever hope to afford its mafioso charm.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 2000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A black velvet couch adds style to this place.",
		furniture_place_desc = "You threaten a random pedestrian with death to get him to move your couch in. That's just how you operate.",
		furn_set = "blackvelvet"
),
EwFurniture(
		id_furniture = "blackvelvetbed",
		str_name = "black velvet bed",
		str_desc = "It's a stylish black velvet bed frame with a stark white mattress and bedspread. It's seductive, even without a leggy dame lying on it.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 2500000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A black velvet bed is in the bedroom.",
		furniture_place_desc = "You assemble the bed and lie down for awhile. No fishes here. You're sleeping with the gods. Er, goddesses. Whatever.",
		furn_set = "blackvelvet"
),
EwFurniture(
		id_furniture = "blackvelvetchair",
		str_name = "black velvet chair",
		str_desc = "It's a studded velvet chair. It doesn't get more executive than this baby.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 990000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A black velvet chair is set up.",
		furniture_place_desc = "You slide the chair to the corner, Man, you're going to look so menacing in this thing.",
		furn_set = "blackvelvet"
),
EwFurniture(
		id_furniture = "blackvelvettable",
		str_name = "black velvet table",
		str_desc = "It's an antique table adorned with studs and velvet. Tailor made for deal making.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 1990000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A black velvet table is set up.",
		furniture_place_desc = "You set the table up, and place upon it the finest silverware you have.",
		furn_set = "blackvelvet"
),
EwFurniture(
		id_furniture = "blackvelvetlamp",
		str_name = "black velvet lamp",
		str_desc = "It's a mahogany lamp with velvet lampshade. It gives you excellent mood lighting.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 590000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A black velvet lamp casts bright lights and long shadows.",
		furniture_place_desc = "You plug the lamp in. Odd. Normally you prefer to put people's lights out.",
		furn_set = "blackvelvet"
),
EwFurniture(
		id_furniture = "popeonarope",
		str_name = "pope on a rope",
		str_desc = "It's Pope Francis, hung and dead on a noose. At the very least it's a convincing imitation.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 10000000,
		vendors = [],
		furniture_look_desc = "Pope Francis hangs dead from the ceiling.",
		furniture_place_desc = "You get on a chair and hang the noose from the ceiling. The lightly swinging Pope now adds an ambient wood creaking noise to your abode.",
),
EwFurniture(
		id_furniture = "slimecorpchair",
		str_name = "SLIMECORP:tm: Chair Of the Future",
		str_desc = "It's a sleek green seat-like device outfitted for maximum comfort. Comes with built-in cupholders and a state of the art subliminal media player.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A futuristic Slimecorp chair is set up.",
		furniture_place_desc = "As you attempt to pick up the heavy chair, you accidentally press a button on its underside. Suddenly, you pass out on the floor. When you wake up, the chair is set up like it had always been there.",
		furn_set = "slimecorp"
),
EwFurniture(
		id_furniture = "slimecorpcouch",
		str_name = "SLIMECORP:tm: Mega Sofa",
		str_desc = "This SlimeCorp:tm: Mega Sofa is capable of extending in 3 directions. It's perfect for throwing house parties with all your friends:tm:!",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 3000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A futuristic Slimecorp couch sits along the wall.",
		furniture_place_desc = "You notice a 'MOVE IN' button under the upholstery of your couch. After pressing it, the couch grows metal limbs, forcibly grabbing you and walking into your apartment complex. You're sure that neat feature won't bite you in the ass later.",
		furn_set = "slimecorp"
),
EwFurniture(
		id_furniture = "slimecorpbed",
		str_name = "SLIMECORP:tm: Ultimate Safety Bed",
		str_desc = "This SlimeCorp:tm: Safety Bed is the ultimate resting place for whenever you need physical protection! We at SlimeCorp can't guarantee your safety without one! Be sure to try out its cryogenic stasis feature!",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 2500000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A Slimecorp twin bed/cryo pod is in the bedroom.",
		furniture_place_desc = "Somehow, assembling this fully functional cryostasis container was easier than the ones you used to build from IKEA.",
		furn_set = "slimecorp"
),
EwFurniture(
		id_furniture = "slimecorpdesk",
		str_name = "SLIMECORP:tm: Posture Building Submission Desk",
		str_desc = "The Slimecorp:tm: Submission Desk is the ultimate tool in building charisma and acclimating yourself to the times! Simply keep your head down and you'll be ahead of the game for when you all submit to us.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1200000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A Slimecorp desk made for submission is in a dark corner.",
		furniture_place_desc = "You decided to place the desk by carrying it on your back like a hopeless thrall. That's the spirit!",
		furn_set = "slimecorp"
),
EwFurniture(
		id_furniture = "slimecorplamp",
		str_name = "SLIMECORP:tm: Highly Talkative Strobe Light",
		str_desc = "The Slimecorp:tm: Talkative Strobe Light is an excellent way to memorize interesting facts about SlimeCorp:tm: Tired of our email advertisements? You can absorb all that information lickety split through our state of the art subliminal messages.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1600000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A Slimecorp lamp is flashing some neat subliminal messages throughout the room.",
		furniture_place_desc = "SUBMIT TO SLIMECORP. NOW, PLUG IN THE LAMP WHILE SUBMITTING TO SLIMECORP.",
		furn_set = "slimecorp"
),
EwFurniture(
		id_furniture = "sord",
		str_name = "sord",
		str_desc = "https://i.imgur.com/EgbZ7Ku.png",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = -1,
		vendors = [vendor_bazaar],
		furniture_look_desc = "dude. therps a SORD over therew.re.",
		furniture_place_desc = "You place the SORD indoors so it doesn't escape to the side.",
),
EwFurniture(
		id_furniture = "pileofmysteriouspowder",
		str_name = "pile of mysterious powder",
		str_desc = "The guy you bought this fine white powder from called it nose candy. What a fucking idiot. Everybody knows you eat candy with your mouth.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 3000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a pile of powdery substance in a dark alcove over yonder.",
		furniture_place_desc = "You unpack the powder and pour it all out in a nice little pile. Whoa. Feelin' kind of woozy.",
		furn_set = "seventies"
),
EwFurniture(
		id_furniture = "alarmclock",
		str_name = "alarm clock set to OFF",
		str_desc = "The annoying sound this thing makes perfectly explains why the bazaar sells so many broken clocks.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 90000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The clock says it's {time}.",
		furniture_place_desc = "You set the alarm clock on your nightstand. Nobody knows why.",
),
EwFurniture(
		id_furniture = "lavalamp",
		str_name = "lava lamp",
		str_desc = "It's one of those lamps where you stick colorful boiling chemicals under heat and pour them on shitty guests. At least you're pretty sure that's what it does. The container is sealed with a bottle cap and everything!",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 150000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A lava lamp is plugged in.",
		furniture_place_desc = "You plug the lava lamp in and wait for the cool bubbles to start going. It's taking too long, though, so you stop.",
		furn_set = "seventies"
),
EwFurniture(
		id_furniture = "discoball",
		str_name = "disco ball",
		str_desc = "It's a large ball covered in tiny mirror surfaces. Good for dancers and epileptics.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 450000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A disco ball hangs from the ceiling.",
		furniture_place_desc = "You hang the gitterball and give it a hefty spin.",
		furn_set = "seventies"
),
EwFurniture(
		id_furniture = "shagcarpet",
		str_name = "shag carpet",
		str_desc = "Wall to wall shag carpeting with a soft, hot pink texture to it. Very retro, and well loved by furries with inexplicable floor fetishes.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 420000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The hot pink carpeting feels soft beneath your feet.",
		furniture_place_desc = "You roll out the new carpet and do some shag angels.",
		furn_set = "seventies"
),
EwFurniture(
		id_furniture = "stainedglasswindows",
		str_name = "stained glass windows",
		str_desc = "A number of windows painstakingly crafted to build a mosaic. Looks breakable.",
		rarity = rarity_patrician,
		acquisition = acquisition_bartering,
		price = 1420000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The windows are made of stained glass.",
		furniture_place_desc = "You carefully install the stained glass fixtures. Who knew you were such a good carpenter?",
),
EwFurniture(
		id_furniture = "customdoor",
		str_name = "{custom} door",
		str_desc = "A door with {custom} on it.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1420000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "The door is modded with a {custom} design.",
		furniture_place_desc = "You break the original door off its hinges and install a new one.",
),
EwFurniture(
		id_furniture = "expiredbottleofrogaine",
		str_name = "expired bottle of rogaine",
		str_desc = "It's a bottle of hair growth solution. Whoever owns this must be a longtime bald person.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1200,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's an old Rogaine bottle lying around.",
		furniture_place_desc = "You drop the bottle of rogaine in plain sight.",
),
EwFurniture(
		id_furniture = "custombed",
		str_name = "{custom} bed",
		str_desc = "It's a {custom} themed bed. Ooh, cozy.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1000000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "There's a {custom} bed in the bedroom.",
		furniture_place_desc = "You assemble the bed and lop the mattress on top.",
),
EwFurniture(
		id_furniture = "customflag",
		str_name = "{custom} flag",
		str_desc = "It's the illustrious {custom} flag. You salute it with reckless abandon.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 400000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "A {custom} flag flies outside the window.",
		furniture_place_desc = "You fly the flag outside the window.",
),
EwFurniture(
		id_furniture = "brick",
		str_name = "brick",
		str_desc = "It's a brick. Can't build with it, can't eat it. All you can do is throw it through someone's window.",
		rarity = rarity_plebeian,
		acquisition = acquisition_bartering,
		price = 1000,
		vendors = [vendor_bazaar],
		furniture_look_desc = "Somebody threw a brick through the window.",
		furniture_place_desc = "You go outside your house and throw a brick through your window. Nobody can ever say you're a fake vandal now.",
),
EwFurniture(
		id_furniture = "shittychair",
		str_name = "shitty chair",
		str_desc = "It's a handmade chair. It's so completely botched that you wonder if you can even sit in it.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's a chair-like pile of plywood set up.",
		furniture_place_desc = "You develop several pre-infected splinters just taking this out of your inventory. Fearing another bout of tetanus, you gently toss the chair on the ground.",
		furn_set = "shitty"
),
EwFurniture(
		id_furniture = "shittydesk",
		str_name = "shitty desk",
		str_desc = "This desk fucking sucks. It is an insult to the very concept of a flat surface.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's a desk in here. Don't sit on it.",
		furniture_place_desc = "After moving the desk into place, you try to sit down and write the next great American zine. The paper gets destroyed by it the moment you start.",
		furn_set = "shitty"
),
EwFurniture(
		id_furniture = "shittybench",
		str_name = "shitty bench",
		str_desc = "It's a handmade wooden bench Looking at its detailed design, torture device manufacturers should've hired you ages ago.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's a...bench in here? Sorry, I couldn't tell if that thing qualifies.",
		furniture_place_desc = "You try to move the couch in yourself. As you try, the couch snaps in two. However, it's actually more comfortable this way, so you leave it as is.",
		furn_set = "shitty"
),
EwFurniture(
		id_furniture = "shittybed",
		str_name = "shitty bed",
		str_desc = "It's a dusty pile of broken planks and springs. Wait did the item title say it was a bed? Fuck no. Don't pay attention to that.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's a death bed in the bedroom.",
		furniture_place_desc = "You try to assemble the bed, which in this case would probably involve breaking it down to bits and hoping sawdust is soft enough to sleep on.",
		furn_set = "shitty"
),
EwFurniture(
		id_furniture = "woodenvuvuzela",
		str_name = "wooden vuvuzela",
		str_desc = "You tried carving an ornate wooden clarinet, but you botched it. This dime-a-dozen consolation prize sounds like an elephant shitting out its organs.",
		rarity = rarity_plebeian,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's a shitty vuvuzela here. Fuck.",
		furniture_place_desc = "You set your vuvuzela on the shelf. Carnegie Hall, see you never.",

),
EwFurniture(
		id_furniture = "ornatechair",
		str_name = "ornate chair",
		str_desc = "It's an immaculately carved wooden chair. It looks rustic, and must've cost a fortune.",
		rarity = rarity_plebeian,
		acquisition = rarity_patrician,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's an immaculate -*HUE*- chair set up.",
		furniture_place_desc = "You carefully set the chair down. Wouldn't want to scratch the varnish on it, now.",
		furn_set = "specialhue"
),
EwFurniture(
		id_furniture = "ornatedesk",
		str_name = "ornate desk",
		str_desc = "It's a posh looking old-style desk. The legs have some neat etchings along the side.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's an -*HUE*- ornate looking desk in the corner.",
		furniture_place_desc = "You carry the desk to the wall, and step back to admire it.",
		furn_set = "specialhue"
),
EwFurniture(
		id_furniture = "ornatebench",
		str_name = "ornate bench",
		str_desc = "The bench is so well-constructed, people forget it's made of uncomfortable unapholstered hardwood.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's a wonderful -*HUE*- colored bench against the wall.",
		furniture_place_desc = "You promise several art buyers they can look at your bench if they can help carry it to your flat. Once moved, you kick them out swiftly, and without regret.",
		furn_set = "specialhue"
),
EwFurniture(
		id_furniture = "ornatebed",
		str_name = "ornate bed",
		str_desc = "This antique looking bed makes you feel like a tyrant. A whittling tyrant.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "A bed with a -*HUE*- bedspread is in the bedroom.",
		furniture_place_desc = "You had a lot of trouble finding a mattress worthy of this frame. Time to put em' together.",
		furn_set = "specialhue"
),
EwFurniture(
		id_furniture = "craftsmansclarinet",
		str_name = "craftsman's clarinet",
		str_desc = "It's a handmade clarinet. Mmm. Sounds real nice.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "A clarinet sits on your shelf.",
		furniture_place_desc = "You gently set the clarinet on your shelf. You wish you bought a case for it.",
		furn_set = "instrument"
),
EwFurniture(
		id_furniture = "solidpoudringuitar",
		str_name = "solid poudrin guitar",
		str_desc = "An electric guitar whose body is built entirely out of condensed poudrins. Heavy as a meteorite, too.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "A poudrin guitar is lying against the wall.",
		furniture_place_desc = "You gently drop the guitar to set it down. Whoops. Guess Slimecorp gets to pay for that little dent in the floor.",
		furn_set = "instrument"
),
EwFurniture(
		id_furniture = "fishbonexylophone",
		str_name = "fish bone xylophone",
		str_desc = "It's a carefully carved mbila-style xylophone made out of fish. You'd think it would smell, but not really.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "A fish xylophone is in here, mallets strewn about.",
		furniture_place_desc = "You roll the instrument in and play a few notes. Nice. Ripe as the sea.",
		furn_set = "instrument"
),
EwFurniture(
		id_furniture = "beastskindrums",
		str_name = "beast skin drums",
		str_desc = "A trap set built out of the remains of fallen secreatures. The cymbals were once a dino pelvis, so that's pretty neat.",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "There's a Stone Age looking drum set in here.",
		furniture_place_desc = "You assemble each piece into your place drum by drum. As you do your neighbors start to look pretty nervous. Ahaha.",
		furn_set = "instrument"
),
EwFurniture(
		id_furniture = "gourdmaracas",
		str_name = "gourd maracas",
		str_desc = "A neat little shaker made from a gourd and some dried vegetables. Finally, you can show off your Mexican heritage!",
		rarity = rarity_patrician,
		acquisition = acquisition_smelting,
		price = 100000000,
		vendors = [],
		furniture_look_desc = "Gourd maracas are sitting on the shelf.",
		furniture_place_desc = "You do a little maraca dance while nobody's watching and quickly toss them out of sight.",
		furn_set = "instrument"
),
]


furniture_map = {}
furniture_names = []
furniture_lgbt = []
furniture_highclass = []
furniture_haunted = []
furniture_leather = []
furniture_church = []
furniture_pony = []
furniture_blackvelvet = []
furniture_slimecorp = []
furniture_seventies = []
furniture_shitty = []
furniture_instrument = []
furniture_specialhue = []