
trauma_list = [
	EwTrauma(
		id_trauma = trauma_id_suicide,
		str_trauma_self = "You are suffering from a tragic case of cowardice.",
		str_trauma = "They are suffering from a tragic case of cowardice.",
		trauma_class = trauma_class_damage,
	),
	EwTrauma(
		id_trauma = trauma_id_betrayal,
		str_trauma_self = "You look anxious around your teammates, wary of betrayal.",
		str_trauma = "They look anxious around their teammates, wary of betrayal.",
		trauma_class = trauma_class_movespeed,
	),
	EwTrauma(
		id_trauma = trauma_id_environment,
		str_trauma_self = "Your death could have resulted any number of situations, mostly related to your own idiocy.",
		str_trauma = "Their death could have come from any number of situations, mostly related to their own idiocy.",
		trauma_class = trauma_class_slimegain,
	),
	EwTrauma( # 1
		id_trauma = weapon_id_revolver,
		str_trauma_self = "You have scarring on both temples, which occasionally bleeds.",
		str_trauma = "They have scarring on both temples, which occasionally bleeds.",
		trauma_class = trauma_class_accuracy,
	),
	EwTrauma( # 2
		id_trauma = weapon_id_dualpistols,
		str_trauma_self = "You have several stitches embroidered into your chest over your numerous bullet wounds.",
		str_trauma = "They have several stitches embroidered into your chest over your numerous bullet wounds.",
		trauma_class = trauma_class_bleeding,
	),
	EwTrauma( # 3
		id_trauma = weapon_id_shotgun,
		str_trauma_self = "You have a few large, gaping holes in your abdomen. Someone could stick their arm through the biggest one.",
		str_trauma = "They have a few large, gaping holes in your abdomen. Someone could stick their arm through the biggest one.",
		trauma_class = trauma_class_bleeding,
	),
	EwTrauma( # 4
		id_trauma = weapon_id_rifle,
		str_trauma_self = "Your torso is riddled with scarred-over bulletholes.",
		str_trauma = "Their torso is riddled with scarred-over bulletholes.",
		trauma_class = trauma_class_bleeding,
	),
	EwTrauma( # 5
		id_trauma = weapon_id_smg,
		str_trauma_self = "Your copious amount of bullet holes trigger onlookers’ Trypophobia.",
		str_trauma = "Their copious amount of bullet holes trigger onlookers’ Trypophobia.",
		trauma_class = trauma_class_bleeding,
	),
	EwTrauma( # 6
		id_trauma = weapon_id_minigun,
		str_trauma_self = "What little is left of your body has large holes punched through it, resembling a slice of swiss cheese.",
		str_trauma = "What little is left of their body has large holes punched through it, resembling a slice of swiss cheese.",
		trauma_class = trauma_class_bleeding,
	),
	EwTrauma( # 7
		id_trauma = weapon_id_bat,
		str_trauma_self = "Your head appears to be slightly concave on one side.",
		str_trauma = "Their head appears to be slightly concave on one side.",
		trauma_class = trauma_class_accuracy,
	),
	EwTrauma( # 8
		id_trauma = weapon_id_brassknuckles,
		str_trauma_self = "You've got two black eyes, missing teeth, and a profoundly crooked nose.",
		str_trauma = "They've got two black eyes, missing teeth, and a profoundly crooked nose.",
		trauma_class = trauma_class_accuracy,
	),
	EwTrauma( # 9
		id_trauma = weapon_id_katana,
		str_trauma_self = "A single clean scar runs across the entire length of your body.",
		str_trauma = "A single clean scar runs across the entire length of their body.",
		trauma_class = trauma_class_hunger,
	),
	EwTrauma( # 10
		id_trauma = weapon_id_broadsword,
		str_trauma_self = "A large dent resembling that of a half-chopped down tree appears on the top of your head.",
		str_trauma = "A dent resembling that of a half-chopped down tree appears on the top of their head.",
		trauma_class = trauma_class_accuracy,
	),
	EwTrauma( # 11
		id_trauma = weapon_id_nunchucks,
		str_trauma_self = "You are covered in deep bruises. You hate martial arts of all kinds.",
		str_trauma = "They are covered in deep bruises. They hate martial arts of all kinds.",
		trauma_class = trauma_class_hunger,
	),
	EwTrauma( # 12
		id_trauma = weapon_id_scythe,
		str_trauma_self = "You are wrapped tightly in bandages that hold your two halves together.",
		str_trauma = "They are wrapped tightly in bandages that hold their two halves together.",
		trauma_class = trauma_class_movespeed,
	),
	EwTrauma( # 13
		id_trauma = weapon_id_yoyo,
		str_trauma_self = "Simple yo-yo tricks caught even in your peripheral vision triggers intense PTSD flashbacks.",
		str_trauma = "Simple yo-yo tricks caught even in their peripheral vision triggers intense PTSD flashbacks.",
		trauma_class = trauma_class_hunger,
	),
	EwTrauma( # 14
		id_trauma = weapon_id_knives,
		str_trauma_self = "You are covered in scarred-over lacerations and puncture wounds.",
		str_trauma = "They are covered in scarred-over lacerations and puncture wounds.",
		trauma_class = trauma_class_bleeding,
	),
	EwTrauma( # 15
		id_trauma = weapon_id_molotov,
		str_trauma_self = "You're wrapped in bandages. What skin is showing appears burn-scarred.",
		str_trauma = "They're wrapped in bandages. What skin is showing appears burn-scarred.",
		trauma_class = trauma_class_hunger,
	),
	EwTrauma( # 16
		id_trauma = weapon_id_grenades,
		str_trauma_self = "Blast scars and burned skin are spread unevenly across your body.",
		str_trauma = "Blast scars and burned skin are spread unevenly across their body.",
		trauma_class = trauma_class_hunger,
	),
	EwTrauma( # 17
		id_trauma = weapon_id_garrote,
		str_trauma_self = "There is noticeable bruising and scarring around your neck.",
		str_trauma = "There is noticeable bruising and scarring around their neck.",
		trauma_class = trauma_class_hunger,
	),
	EwTrauma(  # 18
		id_trauma = weapon_id_pickaxe,
		str_trauma_self = "There is a deep, precise indent in the crown of your skull. How embarrassing!",
		str_trauma = "There is a deep, precise indent in the crown of their skull. How embarrassing!",
		trauma_class = trauma_class_accuracy,
	),
	EwTrauma(  # 19
		id_trauma = "fishingrod",
		str_trauma_self = "There is a piercing on the side of your mouth. How embarrassing!",
		str_trauma = "There is a piercing on the side of their mouth. How embarrassing!",
		trauma_class = trauma_class_hunger,
	),
	EwTrauma(  # 20
		id_trauma = weapon_id_bass,
		str_trauma_self = "There is a large concave dome in the side of your head.",
		str_trauma = "There is a large concave dome in the side of their head.",
		trauma_class = trauma_class_accuracy,
	),
	EwTrauma(  # 21
		id_trauma = weapon_id_umbrella,
		str_trauma_self = "You have a large hole in your chest.",
		str_trauma = "They have a large hole in their chest.",
		trauma_class = trauma_class_bleeding,
	),
	EwTrauma(  # 22
		id_trauma = weapon_id_bow,
		str_trauma_self = "There is a pixelated arrow in the side of your head.",
		str_trauma = "There is a pixelated arrow in the side of their head.",
		trauma_class = trauma_class_accuracy,
	),
	EwTrauma(  # 23
		id_trauma = weapon_id_dclaw,
		str_trauma_self = "Three smoldering claw marks are burned into your flesh, the flames `won't seem to extinguish.",
		str_trauma = "Three smoldering claw marks are burned into their flesh, the flames won't seem to extinguish.",
		trauma_class = trauma_class_sapregeneration,
	),
	EwTrauma( # 1
		id_trauma = "fangs",
		str_trauma_self = "You have bite marks littered throughout your body.",
		str_trauma = "They have bite marks littered throughout their body.",
		trauma_class = trauma_class_bleeding,
	),
	EwTrauma( # 2
		id_trauma = "talons",
		str_trauma_self = "A large section of scars litter your abdomen.",
		str_trauma = "A large section of scars litter their abdomen.",
		trauma_class = trauma_class_hunger,
	),
	EwTrauma( # 4
		id_trauma = "gunk shot",
		str_trauma_self = "Several locations on your body have decayed from the aftermath of horrific radiation.",
		str_trauma = "Several locations on their body have decayed from the aftermath of horrific radiation.",
		trauma_class = trauma_class_sapregeneration,
	),
	EwTrauma( # 5
		id_trauma = "tusks",
		str_trauma_self = "You have one large scarred-over hole on your upper body.",
		str_trauma = "They have one large scarred-over hole on their upper body.",
		trauma_class = trauma_class_bleeding,
	),
	EwTrauma( # 6
		id_trauma = "molotov breath",
		str_trauma_self = "You're wrapped in two layers of bandages. What skin is showing appears burn-scarred.",
		str_trauma = "They're wrapped in two layers of bandages. What skin is showing appears burn-scarred.",
		trauma_class = trauma_class_hunger,
	),
	EwTrauma( # 7
		id_trauma = "arm cannon",
		str_trauma_self = "There's a deep bruising right in the middle of your forehead.",
		str_trauma = "There's a deep bruising right in the middle of their forehead.",
		trauma_class = trauma_class_accuracy,
	),
	EwTrauma( # 8
		id_trauma = "axe",
		str_trauma_self = "There's a hefty amount of bandages covering the top of your head",
		str_trauma = "There's a hefty amount of bandages covering the top of their head",
		trauma_class = trauma_class_accuracy,
	),
	EwTrauma( # 9
		id_trauma = "hooves",
		str_trauma_self = "Your chest is somewhat concave.",
		str_trauma = "Their chest is somewhat concave.",
		trauma_class = trauma_class_hunger,
	),
]

trauma_map = {}