# All weapons in the game.

vendor_dojo = "Dojo"

weapon_class_ammo = "ammo"
weapon_class_thrown = "thrown"
weapon_class_exploding = "exploding"
weapon_class_burning = "burning"
weapon_class_jammable = "jammable"
weapon_class_captcha = "captcha"
weapon_class_defensive = "defensive"
weapon_class_heavy = "heavy"

weapon_list = [
	EwWeapon( # 1
		id_weapon = weapon_id_revolver,
		alias = [
			"pistol",
			"handgun",
			"bigiron"
		],
		str_crit = "**Critical Hit!** You have fataly wounded {name_target} with a lethal shot!",
		str_miss = "**You missed!** Your shot whizzed past {name_target}'s head!",
		str_equip = "You equip the revolver.",
		str_name = "revolver",
		str_weapon = "a revolver",
		str_weaponmaster_self = "You are a rank {rank} master of the revolver.",
		str_weaponmaster = "They are a rank {rank} master of the revolver.",
		#str_trauma_self = "You have scarring on both temples, which occasionally bleeds.",
		#str_trauma = "They have scarring on both temples, which occasionally bleeds.",
		str_kill = "{name_player} puts their revolver to {name_target}'s head. **BANG**. Execution-style. Blood splatters across the hot asphalt. {emote_skull}",
		str_killdescriptor = "gunned down",
		str_damage = "{name_target} takes a bullet to the {hitzone}!!",
		str_duel = "**BANG BANG**. {name_player} and {name_target} practice their quick-draw, bullets whizzing past one another's heads.",
		str_description = "It's a revolver.",
		str_reload = "You swing out the revolver’s chamber, knocking out the used shells onto the floor before hastily slamming fresh bullets back into it.",
		str_reload_warning = "**BANG--** *tk tk...* **SHIT!!** {name_player} just spent the last of the ammo in their revolver’s chamber, it’s out of bullets!!",
		str_scalp = " It has a bullet hole in it.",
		fn_effect = wef_revolver,
		clip_size = 6,
		vendors = [vendor_dojo],
		classes = [weapon_class_ammo, weapon_class_captcha],
		stat = stat_revolver_kills,
		sap_cost = 1,
		captcha_length = 3
	),
	EwWeapon( # 2
		id_weapon = weapon_id_dualpistols,
		alias = [
			"dual",
			"pistols",
			"berettas",
			"dualies"
		],
		str_crit = "**Critical Hit!** {name_player} has lodged several bullets into {name_target}'s vital arteries!",
		str_miss = "**You missed!** Your numerous, haphazard shots hit everything but {name_target}!",
		str_equip = "You equip the dual pistols.",
		str_name = "dual pistols",
		str_weapon = "dual pistols",
		str_weaponmaster_self = "You are a rank {rank} master of the dual pistols.",
		str_weaponmaster = "They are a rank {rank} master of the dual pistols.",
		#str_trauma_self = "You have several stitches embroidered into your chest over your numerous bullet wounds.",
		#str_trauma = "They have several stitches embroidered into your chest over your numerous bullet wounds.",
		str_kill = "{name_player} dramatically pulls both triggers on their dual pistols midair, sending two bullets straight into {name_target}'s lungs'. {emote_skull}",
		str_killdescriptor = "double gunned down",
		str_damage = "{name_target} takes a flurry of bullets to the {hitzone}!!",
		str_duel = "**tk tk tk tk tk tk tk tk tk tk**. {name_player} and {name_target} hone their twitch aim and trigger fingers, unloading clip after clip of airsoft BBs into one another with the eagerness of small children.",
		str_description = "They're dual pistols.",
		str_reload = "You swing out the handles on both of your pistols, knocking out the used magazines onto the floor before hastily slamming fresh mags back into them.",
		str_reload_warning = "**tk tk tk tk--** *tk...* **SHIT!!** {name_player} just spent the last of the ammo in their dual pistol’s mags, they’re out of bullets!!",
		str_scalp = " It has a couple bullet holes in it.",
		fn_effect = wef_dualpistols,
		clip_size = 12,
		price = 10000,
		vendors = [vendor_dojo],
		classes = [weapon_class_ammo, weapon_class_captcha],
		stat = stat_dual_pistols_kills,
		sap_cost = 1,
		captcha_length = 1
	),
	EwWeapon( # 3
		id_weapon = weapon_id_shotgun,
		alias = [
			"boomstick",
			"remington",
			"scattergun",
			"r870"
		],
		str_crit = "**Critical Hit!** {name_player} has landed a thick, meaty shot into {name_target}'s chest!",
		str_miss = "**You missed!** Your pellets inexplicably dodge {name_target}. Fucking random bullet spread, this game will never be competitive.",
		str_equip = "You equip the shotgun.",
		str_name = "shotgun",
		str_weapon = "a shotgun",
		str_weaponmaster_self = "You are a rank {rank} master of the shotgun.",
		str_weaponmaster = "They are a rank {rank} master of the shotgun.",
		#str_trauma_self = "You have a few large, gaping holes in your abdomen. Someone could stick their arm through the biggest one.",
		#str_trauma = "They have a few large, gaping holes in your abdomen. Someone could stick their arm through the biggest one.",
		str_kill = "{name_player} blasts their shotgun into {name_target}'s chest at point-blank range, causing guts to explode from their back and coat the surrounding street. chk chk Who's next? {emote_skull}",
		str_killdescriptor = "pumped full of lead",
		str_damage = "{name_target} takes a shotgun blast to the {hitzone}!!",
		str_duel = "**BOOM.** {name_player} and {name_target} stand about five feet away from a wall, pumping it full of lead over and over to study it's bullet spread.",
		str_description = "It's a shotgun.",
		str_reload = "You tilt your shotgun and pop shell after shell into it’s chamber before cocking the forend back. Groovy.",
		str_reload_warning = "**chk--** *...* **SHIT!!** {name_player}’s shotgun has ejected the last shell in it’s chamber, it’s out of ammo!!",
		str_scalp = " It has a gaping hole in the center.",
		fn_effect = wef_shotgun,
		clip_size = 2,
		price = 10000,
		vendors = [vendor_dojo],
		classes = [weapon_class_ammo, weapon_class_captcha],
		stat = stat_shotgun_kills,
		sap_cost = 4,
		captcha_length = 5
	),
	EwWeapon( # 4
		id_weapon = weapon_id_rifle,
		alias = [
			"assaultrifle",
			"machinegun",
			"mg"
		],
		str_crit = "**Critical hit!!** You unload an entire magazine into the target!!",
		str_miss = "**You missed!** Not one of your bullets connected!!",
		str_equip = "You equip the assault rifle.",
		str_name = "assault rifle",
		str_weapon = "an assault rifle",
		str_weaponmaster_self = "You are a rank {rank} master of the assault rifle.",
		str_weaponmaster = "They are a rank {rank} master of the assault rifle.",
		#str_trauma_self = "Your torso is riddled with scarred-over bulletholes.",
		#str_trauma = "Their torso is riddled with scarred-over bulletholes.",
		str_kill = "**RAT-TAT-TAT-TAT-TAT!!** {name_player} rains a hail of bullets directly into {name_target}!! They're officially toast! {emote_skull}",
		str_killdescriptor = "gunned down",
		str_damage = "Bullets rake over {name_target}'s {hitzone}!!",
		str_duel = "**RAT-TAT-TAT-TAT-TAT!!** {name_player} and {name_target} practice shooting at distant targets with quick, controlled bursts.",
		str_description = "It's a rifle.",
		str_reload = "You hastily rip the spent magazine out of your assault rifle, before slamming a fresh one back into it.",
		str_reload_warning = "**RAT-TAT-TAT--** *ttrrr...* **SHIT!!** {name_player}’s rifle just chewed up the last of it’s magazine, it’s out of bullets!!",
		str_scalp = " It has a shit-load of holes in it.",
		fn_effect = wef_rifle,
		clip_size = 4,
		price = 10000,
		vendors = [vendor_dojo],
		classes = [weapon_class_ammo, weapon_class_captcha],
		stat = stat_rifle_kills,
		sap_cost = 3,
		captcha_length = 4
	),
	EwWeapon( # 5
		id_weapon = weapon_id_smg,
		alias = [
			"submachinegun",
			"machinegun"
		],
		str_crit = "**Critical hit!!** {name_target}’s vital arteries are ruptured by miraculously accurate bullets that actually hit their intended target!!",
		str_miss = "**You missed!!** {name_player}'s reckless aiming sends their barrage of bullets in every direction but into {name_target}’s body!",
		str_equip = "You equip the SMG.",
		str_name = "SMG",
		str_weapon = "an SMG",
		str_weaponmaster_self = "You are a rank {rank} master of the SMG.",
		str_weaponmaster = "They are a rank {rank} master of the SMG.",
		#str_trauma_self = "Your copious amount of bullet holes trigger onlookers’ Trypophobia.",
		#str_trauma = "Their copious amount of bullet holes trigger onlookers’ Trypophobia.",
		str_kill = "**RATTA TATTA TAT!!** {name_player}’s bullet rip through what little was left of {name_target} after the initial barrage. All that remains is a few shreds of clothing and splatterings of slime. {emote_skull}",
		str_killdescriptor = "riddled with bullets",
		str_damage = "A reckless barrage of bullets pummel {name_target}’s {hitzone}!!",
		str_duel = "**RATTA TATTA TAT!!** {name_player} and {name_target} spray bullets across the floor and walls of the Dojo, having a great time.",
		str_description = "It's a submachine gun.",
		str_jammed = "Your SMG jams again, goddamn piece of shit gun...",
		str_reload = "You hastily rip the spent magazine out of your SMG, before slamming a fresh one back into it.",
		str_reload_warning = "**RATTA TATTA--** *tk tk tk tk…* **SHIT!!** {name_player}’s SMG just chewed up the last of it’s magazine, it’s out of bullets!!",
		str_unjam = "{name_player} successfully whacks their SMG hard enough to dislodge whatever hunk of gunk was blocking it’s internal processes.",
		str_scalp = " It has a bunch of holes strewn throughout it.",
		fn_effect = wef_smg,
		clip_size = 4,
		price = 10000,
		vendors = [vendor_dojo],
		classes = [weapon_class_ammo, weapon_class_jammable],
		stat = stat_smg_kills,
		sap_cost = 3,
		captcha_length = 6
	),
	EwWeapon( # 6
		id_weapon = weapon_id_minigun,
		alias = [
			"mini",
			"gatlinggun"
		],
		str_crit = "**Critical hit!!** Round after round of bullets fly through {name_target}, inflicting irreparable damage!!",
		str_miss = "**You missed!!** Despite the growing heap of used ammunition shells {name_player} has accrued, none of their bullets actually hit {name_target}!",
		str_equip = "You equip the minigun.",
		str_name = "minigun",
		str_weapon = "a minigun",
		str_weaponmaster_self = "You are a rank {rank} master of the minigun.",
		str_weaponmaster = "They are a rank {rank} master of the minigun.",
		#str_trauma_self = "What little is left of your body has large holes punched through it, resembling a slice of swiss cheese.",
		#str_trauma = "What little is left of their body has large holes punched through it, resembling a slice of swiss cheese.",
		str_kill = "**TKTKTKTKTKTKTKTKTK!!** {name_player} pushes their minigun barrel right up to {name_target}’s chest, unloading a full round of ammunition and knocking their lifeless corpse back a few yards from the sheer force of the bullets. They failed to outsmart bullet. {emote_skull}",
		str_killdescriptor = "obliterated",
		str_damage = "Cascades of bullet easily puncture and rupture {name_target}’s {hitzone}!!",
		str_duel = "**...** {name_player} and {name_target} crouch close to the ground, throwing sandwiches unto the floor next to each other and repeating memetic voice lines ad nauseam.",
		str_description = "It's a minigun.",
		#str_reload = "You curse under your breath, before pulling a fresh belt of bullets from hammerspace and jamming it into your minigun’s hungry feed.",
		#str_reload_warning = "**TKTKTKTKTKTK--** *wrrrrrr…* **SHIT!!** {name_player}’s minigun just inhaled the last of it’s belt, it’s out of bullets!!",
		str_scalp = " It looks more like a thick slice of swiss cheese than a scalp.",
		fn_effect = wef_minigun,
		price = 1000000,
		vendors = [vendor_bazaar],
		classes= [weapon_class_captcha, weapon_class_heavy],
		stat = stat_minigun_kills,
		sap_cost = 15,
		captcha_length = 10
	),
	EwWeapon( # 7
		id_weapon = weapon_id_bat,
		alias = [
			"club",
			"batwithnails",
			"nailbat",
		],
		str_crit = "**Critical hit!!** {name_player} has bashed {name_target} up real bad!",
		str_miss = "**MISS!!** {name_player} swung wide and didn't even come close!",
		str_equip = "You equip the bat with nails in it.",
		str_name = "bat",
		str_weaponmaster_self = "You are a rank {rank} master of the nailbat.",
		str_weaponmaster = "They are a rank {rank} master of the nailbat.",
		str_weapon = "a bat full of nails",
		#str_trauma_self = "Your head appears to be slightly concave on one side.",
		#str_trauma = "Their head appears to be slightly concave on one side.",
		str_kill = "{name_player} pulls back for a brutal swing! **CRUNCCHHH.** {name_target}'s brains splatter over the sidewalk. {emote_skull}",
		str_killdescriptor = "nail bat battered",
		str_damage = "{name_target} is struck with a hard blow to the {hitzone}!!",
		str_backfire = "{name_player} recklessly budgens themselves with a particularly overzealous swing! Man, how the hell could they fuck up so badly?",
		str_duel = "**SMASHH! CRAASH!!** {name_player} and {name_target} run through the neighborhood, breaking windshields, crushing street signs, and generally having a hell of a time.",
		str_description = "It's a nailbat.",
		str_scalp = " It has a couple nails in it.",
		fn_effect = wef_bat,
		price = 10000,
		vendors = [vendor_dojo],
		classes= [weapon_class_captcha],
		stat = stat_bat_kills,
		sap_cost = 2,
		captcha_length = 2
	),
	EwWeapon( # 8
		id_weapon = weapon_id_brassknuckles,
		alias = [
			"knuckles",
			"knuckledusters",
			"dusters"
		],
		str_crit = "***SKY UPPERCUT!!*** {name_player} executes an artificially difficult combo, rocketing their fist into the bottom of {name_target}’s jaw so hard that {name_target}’s colliding teeth brutally sever an inch off their own tongue!!",
		str_miss = "**MISS!** {name_player} couldn't land a single blow!!",
		str_equip = "You equip the brass knuckles.",
		str_name = "brass knuckles",
		str_weapon = "brass knuckles",
		str_weaponmaster_self = "You are a rank {rank} master pugilist.",
		str_weaponmaster = "They are a rank {rank} master pugilist.",
		#str_trauma_self = "You've got two black eyes, missing teeth, and a profoundly crooked nose.",
		#str_trauma = "They've got two black eyes, missing teeth, and a profoundly crooked nose.",
		str_kill = "{name_player} slugs {name_target} right between the eyes! *POW! THWACK!!* **CRUNCH.** Shit. May have gotten carried away there. Oh, well. {emote_skull}",
		str_killdescriptor = "pummeled to death",
		str_damage = "{name_target} is socked in the {hitzone}!!",
		str_duel = "**POW! BIFF!!** {name_player} and {name_target} take turns punching each other in the abs. It hurts so good.",
		str_description = "They're brass knuckles.",
		str_scalp = " It has bone fragments in it.",
		fn_effect = wef_brassknuckles,
		price = 10000,
		vendors = [vendor_dojo],
		classes= [weapon_class_captcha],
		stat = stat_brassknuckles_kills,
		sap_cost = 1,
		captcha_length = 2
	),
	EwWeapon( # 9
		id_weapon = weapon_id_katana,
		alias = [
			"weebsword",
			"ninjasword",
			"samuraisword",
			"blade"
		],
		str_crit = "**Critical hit!!** {name_target} is cut deep!!",
		str_miss = "",
		str_equip = "You equip the katana.",
		str_name = "katana",
		str_weapon = "a katana",
		str_weaponmaster_self = "You are a rank {rank} blademaster.",
		str_weaponmaster = "They are a rank {rank} blademaster.",
		#str_trauma_self = "A single clean scar runs across the entire length of your body.",
		#str_trauma = "A single clean scar runs across the entire length of their body.",
		str_kill = "Faster than the eye can follow, {name_player}'s blade glints in the greenish light. {name_target} falls over, now in two pieces. {emote_skull}",
		str_killdescriptor = "bisected",
		str_damage = "{name_target} is slashed across the {hitzone}!!",
		str_duel = "**CRACK!! THWACK!! CRACK!!** {name_player} and {name_target} duel with bamboo swords, viciously striking at head, wrist and belly.",
		str_description = "It's a katana.",
		str_scalp = " It seems to have been removed with some precision.",
		fn_effect = wef_katana,
		price = 10000,
		vendors = [vendor_dojo],
		classes= [weapon_class_captcha],
		stat = stat_katana_kills,
		sap_cost = 3,
		captcha_length = 8
	),
	EwWeapon( # 10
		id_weapon = weapon_id_broadsword,
		alias = [
			"sword",
			"highlander",
			"arawheapofiron",
			"eyelander"
		],
  		str_crit = "Critical hit!! {name_player} screams at the top of their lungs and unleashes a devastating overhead swing that maims {name_target}.",
		str_miss = "You missed! You grunt as your failed overhead swing sends ripples through the air.",
		str_backfire = "You feel the bones in your wrists snap as you botch your swing with the heavy blade!! Fucking ouch dawg!",
		str_equip = "You equip the broadsword.",
		str_name = "broadsword",
		str_weapon = "a broadsword",
		str_weaponmaster_self = "You are a rank {rank} berserker.",
		str_weaponmaster = "They are a rank {rank} berserker.",
		#str_trauma_self = "A large dent resembling that of a half-chopped down tree appears on the top of your head.",
		#str_trauma = "A dent resembling that of a half-chopped down tree appears on the top of their head.",
		str_kill = "{name_player} skewers {name_target} through the back to the hilt of their broadsword, before kicking their lifeless corpse onto the street corner in gruseome fashion. {name_player} screams at the top of their lungs. {emote_skull}",
		str_killdescriptor = "slayed",
		str_damage = "{name_target}'s {hitzone} is separated from their body!!",
		str_duel = "SCHWNG SCHWNG! {name_player} and {name_target} scream at the top of their lungs to rehearse their battle cries.",
		str_description = "It's a broadsword.",
		str_reload = "You summon strength and muster might from every muscle on your body to hoist your broadsword up for another swing.",
		str_reload_warning = "**THUD...** {name_player}’s broadsword is too heavy, it’s blade has fallen to the ground!!",
		str_scalp = " It was sloppily lopped off.",
		fn_effect = wef_broadsword,
		clip_size = 1,
		price = 10000,
		vendors = [vendor_dojo],
		classes = [weapon_class_ammo, weapon_class_captcha, weapon_class_heavy],
		stat = stat_broadsword_kills,
		sap_cost = 12,
		captcha_length = 4
	),
	EwWeapon( # 11
		id_weapon = weapon_id_nunchucks,
		alias = [
			"nanchacku",
			"nunchaku",
			"chucks",
			"numchucks",
			"nunchucks"
		],
		str_crit = "**COMBO!** {name_player} strikes {name_target} with a flurry of 5 vicious blows!",
		str_backfire = "**Whack!!** {name_player} fucks up their kung-fu routine and whacks themselves in the head with their own nun-chucks!!",
		str_equip = "You equip the nun-chucks.",
		str_name = "nun-chucks",
		str_weapon = "nun-chucks",
		str_weaponmaster_self = "You are a rank {rank} kung-fu master.",
		str_weaponmaster = "They are a rank {rank} kung-fu master.",
		#str_trauma_self = "You are covered in deep bruises. You hate martial arts of all kinds.",
		#str_trauma = "They are covered in deep bruises. They hate martial arts of all kinds.",
		str_kill = "**HIIII-YAA!!** With expert timing, {name_player} brutally batters {name_target} to death, then strikes a sweet kung-fu pose. {emote_skull}",
		str_killdescriptor = "fatally bludgeoned",
		str_damage = "{name_target} takes {strikes} nun-chuck whacks directly in the {hitzone}!!",
		str_duel = "**HII-YA! HOOOAAAAAHHHH!!** {name_player} and {name_target} twirl wildly around one another, lashing out with kung-fu precision.",
		str_description = "They're nunchucks.",
		str_scalp = " It looks very bruised.",
		fn_effect = wef_nunchucks,
		price = 10000,
		vendors = [vendor_dojo],
		classes= [weapon_class_captcha],
		stat = stat_nunchucks_kills,
		sap_cost = 4,
		captcha_length = 3
	),
	EwWeapon( # 12
		id_weapon = weapon_id_scythe,
		alias = [
			"sickle"
		],
		str_crit = "**Critical hit!!** {name_target} is carved by the wicked curved blade!",
		str_miss = "**MISS!!** {name_player}'s swings wide of the target!",
		str_equip = "You equip the scythe.",
		str_name = "scythe",
		str_weapon = "a scythe",
		str_weaponmaster_self = "You are a rank {rank} master of the scythe.",
		str_weaponmaster = "They are a rank {rank} master of the scythe.",
		#str_trauma_self = "You are wrapped tightly in bandages that hold your two halves together.",
		#str_trauma = "They are wrapped tightly in bandages that hold their two halves together.",
		str_kill = "**SLASHH!!** {name_player}'s scythe cleaves the air, and {name_target} staggers. A moment later, {name_target}'s torso topples off their waist. {emote_skull}",
		str_killdescriptor = "sliced in twain",
		str_damage = "{name_target} is cleaved through the {hitzone}!!",
		str_duel = "**WHOOSH, WHOOSH** {name_player} and {name_target} swing their blades in wide arcs, dodging one another's deadly slashes.",
		str_description = "It's a scythe.",
		str_scalp = " It's cut in two pieces.",
		fn_effect = wef_scythe,
		price = 10000,
		vendors = [vendor_dojo],
		classes= [weapon_class_captcha],
		stat = stat_scythe_kills,
		sap_cost = 6,
		captcha_length = 4
	),
	EwWeapon( # 13
		id_weapon = weapon_id_yoyo,
		alias = [
			"yo-yos",
			"yoyo",
			"yoyos"
		],
		str_crit = "SMAAAASH!! {name_player} pulls off a modified Magic Drop, landing a critical hit on {name_target} just after the rejection!",
		str_miss = "You missed! {name_player} misjudges their yo-yos trajectory and botches an easy trick.",
		str_equip = "You equip the yo-yo.",
		str_name = "yo-yo",
		str_weaponmaster_self = "You are a rank {rank} master of the yo-yo.",
		str_weaponmaster = "They are a rank {rank} master of the yo-yo.",
		str_weapon = "a yo-yo",
		#str_trauma_self = "Simple yo-yo tricks caught even in your peripheral vision triggers intense PTSD flashbacks.",
		#str_trauma = "Simple yo-yo tricks caught even in their peripheral vision triggers intense PTSD flashbacks.",
		str_kill = "{name_player} performs a modified Kwyjibo, effortlessly nailing each step before killing their opponent just ahead of the dismount.",
		str_killdescriptor = "amazed",
		str_damage = "{name_player} used {name_target}'s {hitzone} as a counterweight!!",
		str_duel = "whhzzzzzz {name_player} and {name_target} practice trying to Walk the Dog for hours. It never clicks.",
		str_description = "It's a yo-yo.",
		str_scalp = " It has a ball bearing hidden inside it. You can spin it like a fidget spinner.",
		fn_effect = wef_yoyo,
		price = 10000,
		vendors = [vendor_dojo],
		classes= [weapon_class_captcha],
		stat = stat_yoyo_kills,
		sap_cost = 1,
		captcha_length = 2
	),
	EwWeapon( # 14
		id_weapon = weapon_id_knives,
		alias = [
			"knife",
			"dagger",
			"daggers",
			"throwingknives",
			"throwingknife"
		],
		str_crit = "**Critical hit!!** {name_player}'s knife strikes a vital point!",
		str_miss = "**MISS!!** {name_player}'s knife missed its target!",
		str_equip = "You equip the throwing knives.",
		str_name = "throwing knives",
		str_weapon = "throwing knives",
		str_weaponmaster_self = "You are a rank {rank} master of the throwing knife.",
		str_weaponmaster = "They are a rank {rank} master of the throwing knife.",
		#str_trauma_self = "You are covered in scarred-over lacerations and puncture wounds.",
		#str_trauma = "They are covered in scarred-over lacerations and puncture wounds.",
		str_kill = "A blade flashes through the air!! **THUNK.** {name_target} is a goner, but {name_player} slits their throat before fleeing the scene, just to be safe. {emote_skull}",
		str_killdescriptor = "knifed",
		str_damage = "{name_target} is stuck by a knife in the {hitzone}!!",
		str_duel = "**TING! TING!!** {name_player} and {name_target} take turns hitting one another's knives out of the air.",
		str_description = "They're throwing knives.",
		str_scalp = " It has about a half dozen stab holes in it.",
		fn_effect = wef_knives,
		price = 500,
		vendors = [vendor_dojo],
		classes = [weapon_class_thrown, weapon_class_captcha],
		stat = stat_knives_kills,
		sap_cost = 1,
		captcha_length = 3
	),
	EwWeapon( # 15
		id_weapon = weapon_id_molotov,
		alias = [
			"firebomb",
			"molotovcocktail",
			"bomb",
			"bombs",
			"moly"
		],
		str_backfire = "**Oh, the humanity!!** The bottle bursts in {name_player}'s hand, burning them terribly!!",
		str_miss = "**A dud!!** the rag failed to ignite the molotov!",
		str_crit = "{name_player}’s cocktail shatters at the feet of {name_target}, sending a shower of shattered shards of glass into them!!",
		str_equip = "You equip the molotov cocktail.",
		str_name = "molotov cocktail",
		str_weapon = "molotov cocktails",
		str_weaponmaster_self = "You are a rank {rank} master arsonist.",
		str_weaponmaster = "They are a rank {rank} master arsonist.",
		#str_trauma_self = "You're wrapped in bandages. What skin is showing appears burn-scarred.",
		#str_trauma = "They're wrapped in bandages. What skin is showing appears burn-scarred.",
		str_kill = "**SMASH!** {name_target}'s front window shatters and suddenly flames are everywhere!! The next morning, police report that {name_player} is suspected of arson. {emote_skull}",
		str_killdescriptor = "exploded",
		str_damage = "{name_target} dodges a bottle, but is singed on the {hitzone} by the blast!!",
		str_duel = "{name_player} and {name_target} compare notes on frontier chemistry, seeking the optimal combination of combustibility and fuel efficiency.",
		str_description = "These are glass bottles filled with some good ol' fashioned pyrotechnics.",
		str_scalp = " It's burnt to a crisp!",
		fn_effect = wef_molotov,
		price = 500,
		vendors = [vendor_dojo],
		classes = [weapon_class_thrown, weapon_class_burning, weapon_class_captcha],
		stat = stat_molotov_kills,
		sap_cost = 1,
		captcha_length = 4
	),
	EwWeapon( # 16
		id_weapon = weapon_id_grenades,
		alias = [
			"nades",
			"grenade"
		],
		str_crit = "**Critical hit!!** {name_target} is blown off their feet by the initial explosion, and lacerated by innumerable shards of shrapnel scattering themselves through their body!!",
		str_miss = "**You missed!!** {name_player}’s poor aim sends their grenade into a nearby alleyway, it’s explosion eliciting a Wilhelm scream and the assumed death of an innocent passerby. LOL!!",
		str_equip = "You equip the grenades.",
		str_name = "grenades",
		str_weapon = "a stack of grenades",
		str_weaponmaster_self = "You are a rank {rank} master of the grenades.",
		str_weaponmaster = "They are a rank {rank} master of the grenades.",
		#str_trauma_self = "Blast scars and burned skin are spread unevenly across your body.",
		#str_trauma = "Blast scars and burned skin are spread unevenly across their body.",
		str_kill = "**KA-BOOM!!** {name_player} pulls the safety pin and holds their grenade just long enough to cause it to explode mid air, right in front of {name_target}’s face, blowing it to smithereens. {emote_skull}",
		str_killdescriptor = "exploded",
		str_damage = "{name_player}’s grenade explodes, sending {name_target}’s {hitzone} flying off their body!!",
		str_duel = "**KA-BOOM!!** {name_player} and {name_target} pull the pin out of their grenades and hold it in their hands to get a feel for how long it takes for them to explode. They lose a few body parts in the process.",
		str_description = "A stack of grenades.",
		str_scalp = " It's covered in metallic shrapnel.",
		fn_effect = wef_grenade,
		price = 500,
		vendors = [vendor_dojo],
		classes = [weapon_class_thrown, weapon_class_exploding, weapon_class_captcha],
		stat = stat_grenade_kills,
		sap_cost = 1,
		captcha_length = 3
	),
	EwWeapon( # 17
		id_weapon = weapon_id_garrote,
		alias = [
			"wire",
			"garrotewire",
			"garrottewire"
		],
		str_crit = "**CRITICAL HIT!!** {name_player} got lucky and caught {name_target} completely unaware!!",
		str_miss = "**MISS!** {name_player}'s target got away in time!",
		str_equip = "You equip the garrotte wire.",
		str_name = "garrote wire",
		str_weapon = "a garrotte wire",
		str_weaponmaster_self = "You are a rank {rank} master of the garrotte.",
		str_weaponmaster = "They are a rank {rank} master of the garrotte.",
		#str_trauma_self = "There is noticeable bruising and scarring around your neck.",
		#str_trauma = "There is noticeable bruising and scarring around their neck.",
		str_kill = "{name_player} quietly moves behind {name_target} and... **!!!** After a brief struggle, only a cold body remains. {emote_skull}",
		str_killdescriptor = "garrote wired",
		str_damage = "{name_target} is ensnared by {name_player}'s wire!!",
		str_duel = "{name_player} and {name_target} compare their dexterity by playing Cat's Cradle with deadly wire.",
		str_description = "It's a garrote wire.",
		str_scalp = " It's a deep shade of blue.",
		fn_effect = wef_garrote,
		price = 10000,
		vendors = [vendor_dojo],
		stat = stat_garrote_kills,
		sap_cost = 5,
	),
	EwWeapon(  # 18
		id_weapon = weapon_id_pickaxe,
		alias = [
			"pick",
			"poudrinpickaxe",
			"poudrinpick"
		],
		str_crit = "**Critical hit!!** By sheer dumb luck, {name_player} manages to get a good hit off on {name_target}’s {hitzone}.",
		str_miss = "**MISS!!** {name_player} is too weak to lift their pickaxe!",
		str_equip = "You equip the pickaxe.",
		str_name = "pickaxe",
		str_weapon = "a pickaxe",
		str_weaponmaster_self = "You are a rank {rank} coward of the pickaxe.",
		str_weaponmaster = "They are a rank {rank} coward of the pickaxe.",
		#str_trauma_self = "There is a deep, precise indent in the crown of your skull. How embarrassing!",
		#str_trauma = "There is a deep, precise indent in the crown of their skull. How embarrassing!",
		str_kill = "**THWACK!!** {name_player} summons what little courage they possess to lift the pickaxe above their head and !mine {name_target} to death. How embarrassing! {emote_skull}",
		str_killdescriptor = "!mined",
		str_damage = "{name_target} is lightly tapped on the {hitzone}!!",
		str_duel = "**THWACK, THWACK** {name_player} and {name_target} spend some quality time together, catching up and discussing movies they recently watched or food they recently ate.",
		str_scalp = " It reeks of dirt and poudrins. How embarrassing!",
		fn_effect = wef_tool,
		str_description = "It's a pickaxe.",
		acquisition = acquisition_smelting,
		stat = stat_pickaxe_kills,
		sap_cost = 2,
		captcha_length = 2
	),
	EwWeapon(  # 19
		id_weapon = "fishingrod",
		alias = [
			"fish",
			"fishing",
			"rod",
			"super",
			"superrod",
			"superfishingrod"
		],
		str_crit = "**Critical hit!!** By sheer dumb luck, {name_player} manages to get a good hit off on {name_target}’s {hitzone}.",
		str_miss = "**MISS!!** {name_player} is too weak to cast their fishing rod!",
		str_equip = "You equip the super fishing rod.",
		str_name = "super fishing rod",
		str_weapon = "a super fishing rod",
		str_weaponmaster_self = "You are a rank {rank} coward of the super fishing rod.",
		str_weaponmaster = "They are a rank {rank} coward of the super fishing rod.",
		#str_trauma_self = "There is a piercing on the side of your mouth. How embarrassing!",
		#str_trauma = "There is a piercing on the side of their mouth. How embarrassing!",
		str_kill = "*whsssh* {name_player} summons what little courage they possess to reel in {name_target} and wring all the slime out of them. How embarrassing! {emote_skull}",
		str_killdescriptor = "!reeled",
		str_damage = "{name_target} is lightly pierced on the {hitzone}!!",
		str_duel = "**whsssh, whsssh** {name_player} and {name_target} spend some quality time together,discussing fishing strategy and preferred types of bait.",
		str_scalp = " It has a fishing hook stuck in it. How embarrassing!",
		fn_effect = wef_tool,
		str_description = "It's a super fishing rod.",
		acquisition = acquisition_smelting,
		stat = stat_fishingrod_kills,
		sap_cost = 2,
		captcha_length = 2
	),
	EwWeapon(  # 20
		id_weapon = weapon_id_bass,
		alias = [
			"bass",
		],
		str_crit = "**Critical hit!!** Through skilled swipes {name_player} manages to sharply strike {name_target}’s {hitzone}.",
		str_miss = "**MISS!!** {name_player} swings and misses like a dumbass!",
		str_equip = "You equip the bass guitar, a highly distorted and reverbed riff of unknown origin plays as you place the strap over your neck.",
		str_name = "bass guitar",
		str_weapon = "a bass guitar",
		str_weaponmaster_self = "You are a rank {rank} master of the bass guitar.",
		str_weaponmaster = "They are a rank {rank} master of the bass guitar.",
		#str_trauma_self = "There is a large concave dome in the side of your head.",
		#str_trauma = "There is a large concave dome in the side of their head.",
		str_kill = "*CRASSHHH.* {name_player} brings down the bass with righteous fury. Discordant notes play harshly as the bass trys its hardest to keep itself together. {emote_skull}",
		str_killdescriptor = "smashed to pieces",
		str_damage = "{name_target} is whacked across the {hitzone}!!",
		str_duel = "**SMASHHH.** {name_player} and {name_target} smash their bass together before admiring eachothers skillful basslines.",
		str_scalp = " If you listen closely, you can still hear the echoes of a sick bassline from yesteryear.",
		fn_effect = wef_bass,
		str_description = "It's a bass guitar. All of its strings are completely out of tune and rusted.",
		acquisition = acquisition_smelting,
		stat = stat_bass_kills,
		sap_cost = 2,
		captcha_length = 2
	),
	EwWeapon(  # 21
		id_weapon = weapon_id_umbrella,
		alias = [
			"umbrella",
			"slimebrella",
			"slimecorpumbrella"
		],
		str_crit = "**Critical hit!!** {name_player} briefly stuns {name_target} by opening their umbrella in their face, using the opportunity to score a devastating blow to their {hitzone}.",
		str_miss = "**MISS!!** {name_player} fiddles with their umbrella, failing to open it!",
		str_equip = "You equip the umbrella.",
		str_name = "umbrella",
		str_weapon = "an umbrella",
		str_weaponmaster_self = "You are a rank {rank} master of the umbrella.",
		str_weaponmaster = "They are a rank {rank} master of the umbrella.",
		#str_trauma_self = "You have a large hole in your chest.",
		#str_trauma = "They have a large hole in their chest.",
		str_kill = "*SPLAT.* {name_player} pierces {name_target} through the chest, hoists them over their head and opens their umbrella, causing them to explode in a rain of blood and slime. {emote_skull}",
		str_killdescriptor = "umbrella'd",
		str_damage = "{name_target} is struck in the {hitzone}!!",
		str_duel = "**THWACK THWACK.** {name_player} and {name_target} practice their fencing technique, before comparing their favorite umbrella patterns.",
		str_scalp = " At least it didn't get wet.",
		fn_effect = wef_umbrella,
		str_description = "It's an umbrella, both stylish and deadly.",
		price = 100000,
		vendors = [vendor_bazaar],
		classes = [weapon_class_captcha, weapon_class_defensive],
		stat = stat_umbrella_kills,
		sap_cost = 1,
		captcha_length = 4
	),
	EwWeapon(  # 22
		id_weapon = weapon_id_bow,
		alias = [
			"bow",
		],
		str_crit = "**Critical hit!!** Through measured shots {name_player} manages to stick a pixelated arrow in {name_target}’s {hitzone}.",
		str_miss = "**MISS!!** {name_player} completely misses, a pixelated arrow embeds itself into the ground!",
		str_equip = "You equip the minecraft bow, c418 music plays in the background.",
		str_name = "minecraft bow",
		str_weapon = "a minecraft bow",
		str_weaponmaster_self = "You are a rank {rank} minecraft bowmaster.",
		str_weaponmaster = "They are a rank {rank} minecraft bowmaster.",
		#str_trauma_self = "There is a pixelated arrow in the side of your head.",
		#str_trauma = "There is a pixelated arrow in the side of their head.",
		str_kill = "*Pew Pew Pew.* {name_player} spams the bow as their foes life fades, riddling their body with arrows. {emote_skull}",
		str_killdescriptor = "shot to death",
		str_damage = "{name_target} is shot in the {hitzone}!!",
		str_duel = "{name_player} and {name_target} shoot distant targets, {name_player} is clearly the superior bowman.",
		str_scalp = " The scalp has pixels covering it.",
		fn_effect = wef_bow,
		str_description = "It's a newly crafted minecraft bow, complete with a set of minecraft arrows",
		acquisition = acquisition_smelting,
		stat = stat_bow_kills,
		sap_cost = 2,
		captcha_length = 2
	),
		EwWeapon(  # 23
		id_weapon = weapon_id_dclaw,
		alias = [
			"dragon claw",
		],
		str_crit = "{name_player} runs like a madman towards {name_target}, {name_target} swings but is deftly parried by {name_player}, {name_player} hoists their dragon claw into the air and ripostes {name_target} for massive damage ***!!!Critical Hit!!!***",
		str_miss = "{name_player} swings but {name_target} is in the middle of a dodge roll and is protected by iframes. **!!Miss!!**",
		str_equip = "You place the core of the dragon claw on your hand and it unfolds around it, conforming to the contour of your hands, claws protude out the end of your fingers as your hand completes its transformation into the *dragon claw*.",
		str_name = "dragon claw",
		str_weapon = "a dragon claw",
		str_weaponmaster_self = "You are a rank {rank} master of the dragon claw.",
		str_weaponmaster = "They are a rank {rank} master of the dragon claw.",
		#str_trauma_self = "Three smoldering claw marks are burned into your flesh, the flames `won't seem to extinguish.",
		#str_trauma = "Three smoldering claw marks are burned into their flesh, the flames won't seem to extinguish.",
		str_kill = "***Thwip.*** {name_player}'s dragon claw cuts the air followed by a trail of flame and blood, the camera pans out and {name_target} is shown, cut in twain. {emote_skull}",
		str_killdescriptor = "cut to pieces",
		str_damage = random.choice(["{name_target} is slashed across the {hitzone}!!","{name_player} furiously slashes {name_target} across the {hitzone}!!","{name_player} flicks their fingers and a jet of flame ignites from the dragon claw, burning {name_target} in the {hitzone}!!"]),
		str_duel = "**SLICE!! SWIPE!! SLASH!!** {name_player} and {name_target} cut the fuck out of eachother, a fire extinguisher is never more than a meter away.",
		str_scalp = "The scalp is burning and doesn't look like it's gonna stop.",
		fn_effect = wef_dclaw,
		str_description = "It's the core of a Dragon Claw, it will morph around whatever hand it is held by granting them the power of the elusive GREEN EYES SLIME DRAGON. If you listen closely you can hear whines of the dragon soul as it remains perpetually trapped in the weapon.",
		acquisition = acquisition_smelting,
		stat = stat_dclaw_kills,
		classes = [weapon_class_burning],
		sap_cost = 5,
		captcha_length = 2)
]


weapon_vendors = [
	vendor_dojo
]

# A map of id_weapon to EwWeapon objects.
weapon_map = {}

# A list of weapon names
weapon_names = []