
curse_words = { # words that the player should be punished for saying via swear jar deduction. the higher number, the more the player gets punished.
	"fag":30,
	"shit":10,
	"asshole":10, # can not be shortened to 'ass' due to words like 'pass' or 'class'
	"dumbass": 10,
	"cunt":30,
	"fuck":10,
	"bitch":10,
	"bastard":5,
	"nigger":80,
	"kike":80,
	"cuck":30,
	#"chink":50,
	"chinaman":50,
	"gook":50,
	"injun":50,
	"bomboclaat":80,
	"mick":50,
	"pickaninny":50,
	"tarbaby":50,
	"towelhead":50,
	"wetback":50,
	"zipperhead":50,
	"spick":50,
	"dyke":50,
	"tranny":80,
	"dickhead":20,
	"retard":20,
	"buster":100,
	"kraker":100,
	"beaner":50,
	"wanker":10,
	"twat":10,
}

curse_responses = [ # scold the player for swearing
	"Watch your language!",
	"Another one for the swear jar...",
	"Do you kiss your mother with that mouth?",
	"Wow, maybe next time be a little nicer, won't you?",
	"If you don't have anything nice to say, then don't say anything at all.",
	"Wow, racist much???",
	"Now that's just plain rude.",
	"And just like that, some of your precious SlimeCoin goes right down the drain.",
	"Calm down that attitude of yours, will you?",
	"Your bad manners have costed you a fraction of your SlimeCoin!",
	"Take your anger out on a juvenile, if you're so inclined to use such vulgar language.",
	#"You know, don't, say, s-swears."
]
